---
vm_vars:
  kubernetes:
    helm:
      chart:
        name: victoria-metrics
        version: "0.2.0"
      repository:
        name: victoriametrics
        url: https://victoriametrics.github.io/helm-charts/
    operator: # installs the operator crd
      enable: true
      resources:
        limits:
          cpu: null
          memory: 128mi
        requests:
          cpu: 10m
          memory: 128mi
    vmsingle: # creates a single pod vm cluster (non-HA) crds
      enable: true
      resources:
        limits:
          cpu: null
          memory: 2048Mi
        requests:
          cpu: 10m
          memory: 2048Mi
    alertmanager: # installs alertmanager crd
      enable: false
    vmalert: # Crd for defining alert rules
      enable: false
    vmagent: # agent for collecting metrics from sources
      enable: true
      spec:
        scrapeInterval: 25s
    grafana: 
      enable: true
      replicas: 1
      ingress:
        enable: false # enable this later to expose it to ingress for internet access
      admin:
        existingSecret: ""
        username: admin
        password: admin
      resources:
        limits:
          cpu: null
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 256Mi
    prometheus-node-exporter:
      enabled: true
      resources: 
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    kube-state-metrics:
      replicas: 1
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    kubeEtcd: # this scrapes etcd
      enable: false
