- name: Set Redis env variables
  vars:
    redis_env_data: "{{ lookup('ansible.builtin.template', './env/env.yaml' ) | from_yaml }}"
  ansible.builtin.set_fact:
    redis_password: "{{ redis_env_data['redis_pass'] }}"

- name: Deploy Redis on ArgoCD
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'argocd-deployment.j2') | from_yaml }}"