- name: Reboot
  ansible.builtin.reboot:

- name: Restart loadbalancer services
  ansible.builtin.systemd_service:

- name: Restart unattended upgrades service
  ansible.builtin.systemd_service:
    name: unattended-upgrades.service
    state: restarted
    enabled: true