# keyboard specific terms, Gasket-mounted, QKM, HE, CNC, Wireless

KEYBOARD_MODEL_TO_BRAND = {
    # ai03 keyboards
    "Vega": "ai03",
    "Polaris": "ai03",
    "Vector": "ai03",
    "Altair": "ai03",
    "Altair-X": "ai03",
    "Meridian": "ai03",
    "Equinox": "ai03",
    "Equinox XL": "ai03",
    "Photon": "ai03",
    "Andromeda": "ai03",
    "Brutal V2": "ai03",
    # Akko keyboards
    "ACR59": "Akko",
    "ACR61": "Akko",
    "Air 01": "Akko",
    "Gem 01": "Akko",
    "Gem 02": "Akko",
    "JIN01": "Akko",
    "Mineral 01": "Akko",
    "Mineral 02": "Akko",
    # Note: People mention Mod 001 and Mod001, need to find a way to fix this
    "MOD001": "Akko",
    "MOD003": "Akko",
    "MOD004": "Akko",
    "MOD005": "Akko",
    "MOD006": "Akko",
    "MOD007": "Akko",
    "MOD007B": "Akko",
    "MOD007 V1": "Akko",
    "MOD007 V2": "Akko",
    "MOD007 V3": "Akko",
    "MOD007 V5": "Akko",
    "MOD008": "Akko",
    "MU01": "Akko",
    "MU02": "Akko",
    "TAC75": "Akko",
    "TAC87": "Akko",
    "3061S": "Akko",
    "3067B Plus": "Akko",
    "3068v2": "Akko",
    "3068B Plus": "Akko",
    "3084B Plus": "Akko",
    "3084S": "Akko",
    "3087DS": "Akko",
    "3087SP": "Akko",
    "3087v3": "Akko",
    "3087 V1": "Akko",
    "3096DS": "Akko",
    "3098B Plus": "Akko",
    "3098DS": "Akko",
    "3098N": "Akko",
    "3098S": "Akko",
    "3108DS": "Akko",
    "3108OSA": "Akko",
    "3108RF": "Akko",
    "3108v2": "Akko",
    "3108v3": "Akko",
    "5075B Plus": "Akko",
    "5075 V3": "Akko",
    "5087S": "Akko",
    "5087 V2": "Akko",
    "5087 V3": "Akko",
    "5098B": "Akko",
    "5098B Plus": "Akko",
    "5108B": "Akko",
    "5108S": "Akko",
    "5108B Plus": "Akko",
    "6104S": "Akko",
    # Anne Pro keyboards
    "Anne Pro": "",
    "Anne Pro 2": "",
    "Anne Pro 2D": "",
    # Asus ROG keyboards
    "Azoth": "Asus ROG",
    "Azoth Extreme": "Asus ROG",
    "Azoth X": "Asus ROG",
    "Azoth 96 HE": "Asus ROG",
    "Claymore II": "Asus ROG",
    "Falcata": "Asus ROG",
    "Falchion Ace HFX": "Asus ROG",
    "Falchion Ace 75 HE": "Asus ROG",
    "Falchion NX": "Asus ROG",
    "Falchion RX": "Asus ROG",
    "Strix Scope": "Asus ROG",
    "Strix Scope NX": "Asus ROG",
    "Strix Scope RX": "Asus ROG",
    "Strix Scope II X": "Asus ROG",
    "Strix Scope II 96": "Asus ROG",
    # Corsair keyboards
    "Galleon 100 SD": "Corsair",
    "Vanguard 96": "Corsair",
    "Vanguard Pro 96": "Corsair",
    "K55 Core": "Corsair",
    "K55 RGB Pro": "Corsair",
    "K55 RGB Pro Lite": "Corsair",
    "K57": "Corsair",
    "K60 Pro": "Corsair",
    "K65 Plus": "Corsair",
    "K65 Pro Mini": "Corsair",
    "K65 RGB Mini": "Corsair",
    "K70 Core": "Corsair",
    "K70 RGB Pro": "Corsair",
    "K70 Pro": "Corsair",
    "K70 Pro Mini": "Corsair",
    "K70 Max": "Corsair",
    "K95": "Corsair",
    "K95 RGB Platinum": "Corsair",
    "K100": "Corsair",
    "K100 Air": "Corsair",
    "K100 OPX": "Corsair",
    "MAKR PRO 75": "Corsair",
    "Strafe": "Corsair",
    # Drop Keyboards
    "CSTM65": "Drop",
    "CSTM80": "Drop",
    "CTRL": "Drop",
    "ENTR": "Drop",
    "Rainy75": "Drop",
    # Ducky Keyboards
    "OK-M": "Ducky",
    "One X": "Ducky",
    "One X Mini": "Ducky",
    "One 2": "Ducky",
    "One 2 Mini": "Ducky",
    "One 2 Pro": "Ducky",
    "One 3": "Ducky",
    "One 3 Mini": "Ducky",
    "One 3 Pro": "Ducky",
    "Mecha": "Ducky",
    "Mecha Mini": "Ducky",
    "Mecha Pro": "Ducky",
    "Strata 98": "Ducky",
    "Strata 75": "Ducky",
    # Epomaker keyboards
    "Alice 60": "Epomaker",
    "Alice 66": "Epomaker",
    "Carbon60": "Epomaker",
    "EA75": "Epomaker",
    "EA75 Max": "Epomaker",
    "Galaxy65": "Epomaker",
    "Galaxy68": "Epomaker",
    "Galaxy70": "Epomaker",
    "Galaxy100": "Epomaker",
    "Galaxy100 Lite": "Epomaker",
    "G84": "Epomaker",
    "G84 Pro": "Epomaker",
    "Hack59": "Epomaker",
    "HE30": "Epomaker",
    "HE65 Mec": "Epomaker",
    "HE65 Mag": "Epomaker",
    "HE68": "Epomaker",
    "HE75 Mag": "Epomaker",
    "HE80": "Epomaker",
    "Luma40": "Epomaker",
    "Luma84": "Epomaker",
    "QK108": "Epomaker",
    "Magcore 65 Lite": "Epomaker",
    "Magcore 87": "Epomaker",
    "Magforce 68": "Epomaker",
    "P65": "Epomaker",
    "P75": "Epomaker",
    "P87": "Epomaker",
    "RT82": "Epomaker",
    "RT85": "Epomaker",
    "Split70": "Epomaker",
    "Split 65": "Epomaker",
    "TH40": "Epomaker",
    "TH85": "Epomaker",
    "TH87": "Epomaker",
    "TH99": "Epomaker",
    "TH99 Pro": "Epomaker",
    "TH108": "Epomaker",
    "TH108 Pro": "Epomaker",
    # Glorious / GMMK keyboards
    "GMMK": "",
    "GMMK Pro": "",
    "GMMK 2": "",
    "GMMK 3": "",
    "GMMK 3 Pro": "",
    # HHKB keyboards
    "Classic Type-S": "HHKB Professional",
    "Hybrid Type-S": "HHKB Professional",
    "Professional Classic": "HHKB",
    "Professional Hybrid": "HHKB",
    # HyperX keyboards
    "Alloy Core": "HyperX",
    "Alloy Origins": "HyperX",
    "Alloy Origins Core": "HyperX",
    "Alloy Rise": "HyperX",
    "Eve 1800": "HyperX",
    "Origins 2 65": "HyperX",
    "Origins 2 1800": "HyperX",
    # KBDfans keyboards
    "Agar": "KBDfans",
    "Agar Mini": "KBDfans",
    "Athena 1800": "KBDfans",
    "Dusk 67": "KBDfans",
    "Eden R2": "KBDfans",
    "Holy60": "KBDfans",
    "KBD8X MKIII": "KBDfans",
    "Margo": "KBDfans",
    "Nono N65": "KBDfans",
    "Nono N67": "KBDfans",
    "Onibi": "KBDfans",
    "Smurve80": "KBDfans",
    "S73": "KBDfans",
    "Tofu60": "KBDfans",
    "Tofu60 2.0": "KBDfans",
    "Tofu60 3.0": "KBDfans",
    "Tofu65": "KBDfans",
    # Keychron keyboards
    "B1 Pro": "Keychron",
    "B2 Pro": "Keychron",
    "B3 Pro": "Keychron",
    "B4 Pro": "Keychron",
    "B5 Pro": "Keychron",
    "B6 Pro": "Keychron",
    "B31": "Keychron",
    "B33": "Keychron",
    "B35": "Keychron",
    "B36": "Keychron",
    "C1": "Keychron",
    "C1 Pro": "Keychron",
    "C2": "Keychron",
    "C2 Pro": "Keychron",
    "C3 Pro": "Keychron",
    "C4 HE": "Keychron",
    "J1": "Keychron",
    "J2": "Keychron",
    "J4": "Keychron",
    "J5": "Keychron",
    "K1": "Keychron",
    "K1 Max": "Keychron",
    "K1 Pro": "Keychron",
    "K2": "Keychron",
    "K2 HE": "Keychron",
    "K2 Max": "Keychron",
    "K2 Pro": "Keychron",
    "K3": "Keychron",
    "K3 Max": "Keychron",
    "K3 Pro": "Keychron",
    "K4": "Keychron",
    "K4 HE": "Keychron",
    "K4 Max": "Keychron",
    "K4 Pro": "Keychron",
    "K5": "Keychron",
    "K5 Max": "Keychron",
    "K5 Pro": "Keychron",
    "K6": "Keychron",
    "K6 HE": "Keychron",
    "K6 Pro": "Keychron",
    "K7": "Keychron",
    "K7 Max": "Keychron",
    "K7 Pro": "Keychron",
    "K8": "Keychron",
    "K8 HE": "Keychron",
    "K8 Max": "Keychron",
    "K8 Pro": "Keychron",
    "K9 Max": "Keychron",
    "K9 Pro": "Keychron",
    "K10": "Keychron",
    "K10 Max": "Keychron",
    "K10 Pro": "Keychron",
    "K11 Max": "Keychron",
    "K11 Pro": "Keychron",
    "K12": "Keychron",
    "K12 Pro": "Keychron",
    "K13 Max": "Keychron",
    "K13 Pro": "Keychron",
    "K14": "Keychron",
    "K14 Pro": "Keychron",
    "K15 Max": "Keychron",
    "K15 Pro": "Keychron",
    "K17 Max": "Keychron",
    "K17 Pro": "Keychron",
    "P3 HE": "Keychron",
    "Q1": "Keychron",
    "Q1 HE": "Keychron",
    "Q1 Max": "Keychron",
    "Q1 Pro": "Keychron",
    "Q1 Ultra": "Keychron",
    "Q2": "Keychron",
    "Q2 HE": "Keychron",
    "Q2 Max": "Keychron",
    "Q2 Pro": "Keychron",
    "Q3": "Keychron",
    "Q3 HE": "Keychron",
    "Q3 Max": "Keychron",
    "Q3 Pro": "Keychron",
    "Q3 Ultra": "Keychron",
    "Q4": "Keychron",
    "Q4 HE": "Keychron",
    "Q4 Pro": "Keychron",
    "Q5": "Keychron",
    "Q5 HE": "Keychron",
    "Q5 Max": "Keychron",
    "Q5 Pro": "Keychron",
    "Q6": "Keychron",
    "Q6 HE": "Keychron",
    "Q6 Max": "Keychron",
    "Q6 Pro": "Keychron",
    "Q6 Ultra": "Keychron",
    "Q7": "Keychron",
    "Q8": "Keychron",
    "Q8 Max": "Keychron",
    "Q8 Pro": "Keychron",
    "Q9": "Keychron",
    "Q10": "Keychron",
    "Q10 Max": "Keychron",
    "Q10 Pro": "Keychron",
    "Q11": "Keychron",
    "Q12": "Keychron",
    "Q12 HE": "Keychron",
    "Q12 Max": "Keychron",
    "Q13 Max": "Keychron",
    "Q13 Pro": "Keychron",
    "Q14 Max": "Keychron",
    "Q14 Pro": "Keychron",
    "Q15 Max": "Keychron",
    "Q16 HE": "Keychron",
    "Q60": "Keychron",
    "Q60 Max": "Keychron",
    "Q65": "Keychron",
    "Q65 Max": "Keychron",
    "S1": "Keychron",
    "V1": "Keychron",
    "V1 Max": "Keychron",
    "V1 Ultra": "Keychron",
    "V2": "Keychron",
    "V2 Max": "Keychron",
    "V3": "Keychron",
    "V3 Max": "Keychron",
    "V3 Ultra": "Keychron",
    "V4": "Keychron",
    "V4 Max": "Keychron",
    "V5": "Keychron",
    "V5 Max": "Keychron",
    "V5 Ultra": "Keychron",
    "V6": "Keychron",
    "V6 Max": "Keychron",
    "V6 Ultra": "Keychron",
    "V7": "Keychron",
    "V8": "Keychron",
    "V10": "Keychron",
    "V10 Max": "Keychron",
    # Leopold keyboards
    "FC630MBT": "Leopold",
    "FC650MDS": "Leopold",
    "FC650MDSBT": "Leopold",
    "FC660C": "Leopold",
    "FC660M": "Leopold",
    "FC660MBT": "Leopold",
    "FC730MBT V2": "Leopold",
    "FC750R": "Leopold",
    "FC750RBT": "Leopold",
    "FC750RBT V2": "Leopold",
    "FC900R": "Leopold",
    "FC900RBT": "Leopold",
    "FC900RBT V2": "Leopold",
    "FC980C": "Leopold",
    "FC980M": "Leopold",
    "FC980MBT": "Leopold",
    "NP900RBT": "Leopold",
    # Logitech keyboards
    "Alto Keys K98M": "Logitech",
    "K845": "Logitech",
    "MX Mechanical": "Logitech",
    "MX Mechanical Mini": "Logitech",
    "G213 Prodigy": "Logitech G",
    "G413": "Logitech G",
    "G413 SE": "Logitech G",
    "G512": "Logitech G",
    "G515": "Logitech G",
    "G515 Lightspeed": "Logitech G",
    "G515 Rapid": "Logitech G",
    "G713": "Logitech G",
    "G715": "Logitech G",
    "G815": "Logitech G",
    "G915 X": "Logitech G",
    "G915 X Lightspeed": "Logitech G",
    "Pro X TKL Rapid": "Logitech G",
    "Pro X 60": "Logitech G",
    # Nuphy keyboards
    "Air60": "NuPhy",
    "Air60 V2": "NuPhy",
    "Air75": "NuPhy",
    "Air75 V2": "NuPhy",
    "Air75 V3": "NuPhy",
    "Air96": "NuPhy",
    "Air96 V2": "NuPhy",
    "Field75": "NuPhy",
    "Gem80": "NuPhy",
    "Halo65": "NuPhy",
    "Halo65 V2": "NuPhy",
    "Halo75": "NuPhy",
    "Halo75 V2": "NuPhy",
    "Halo96": "NuPhy",
    "Halo96 V2": "NuPhy",
    "Kick75": "NuPhy",
    "Nos75": "NuPhy",
    # Razer keyboards
    "Blackwidow V3": "Razer",
    "Blackwidow V3 Mini": "Razer",
    "BlackWidow V4": "Razer",
    "BlackWidow V4 Pro": "Razer",
    "BlackWidow V4 X": "Razer",
    "DeathStalker V2": "Razer",
    "DeathStalker V2 Pro": "Razer",
    "Huntsman Mini": "Razer",
    "Huntsman Tournament": "Razer",
    "Huntsman V2": "Razer",
    "Huntsman V3 Pro": "Razer",
    "Huntsman V3 Pro Mini": "Razer",
    "Ornata V3": "Razer",
    "Ornata V3 X": "Razer",
    "Pro Type Ultra": "Razer",
    # Royal Kludge keyboards - Lots of people abreviate Royal Kludge as RK
    "A72": "Royal Kludge",
    "C68": "Royal Kludge",
    "C84": "Royal Kludge",
    "C87": "Royal Kludge",
    "C96": "Royal Kludge",
    "C98": "Royal Kludge",
    "F68": "Royal Kludge",
    "F99": "Royal Kludge",
    "L75": "Royal Kludge",
    "L98": "Royal Kludge",
    "M87": "Royal Kludge",
    "N80": "Royal Kludge",
    "R65": "Royal Kludge",
    "R75": "Royal Kludge",
    "R87 Pro": "Royal Kludge",
    "RK61": "Royal Kludge",
    "RK68": "Royal Kludge",
    "RK84": "Royal Kludge",
    "RK84 Pro": "Royal Kludge",
    "RK89": "Royal Kludge",
    "RK920": "Royal Kludge",
    "RK96": "Royal Kludge",
    "S85": "Royal Kludge",
    "S98": "Royal Kludge",
    # SteelSeries keyboards
    "Apex Pro": "SteelSeries",
    "Apex Pro Mini": "SteelSeries",
    "Apex 3": "SteelSeries",
    "Apex 5": "SteelSeries",
    "Apex 7": "SteelSeries",
    "Apex 9": "SteelSeries",
    "Apex 9 Mini": "SteelSeries",
    "Apex 100": "SteelSeries",
    # Wooting keyboards
    "60HE": "Wooting",
    "60HE+": "Wooting",
    "60HE v2": "Wooting",
    "80HE": "Wooting",
    "Two HE": "Wooting",
    # Varmilo keyboards
    "Minilo": "Varmilo",
    "Minilo75 HE": "Varmilo",
    "Minilo75 Pro": "Varmilo",
    "Minilo98 Pro": "Varmilo",
    "Muse65 HE": "Varmilo",
    "Sword68": "Varmilo",
    "VA80 Hygge": "Varmilo",
    "VA100": "Varmilo",
}