apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: cyphria-frontend-argo-cd-deployment
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: https://github.com/Vchen7629/Cyphria
    targetRevision: main
  
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend