exclude = [
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
    ".venv",
    "__pycache__",
    ".github",
    "frontend",
    "kafka",
    "kubernetes",
    "loginapi",
    "monitoring",
]

line-length = 100
indent-width = 4

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = false
line-ending = "auto"