apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: loginapi-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cyphria-loginapi-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: AverageValue
          averageValue: 500m