apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyphria-loginapi-deployment
  labels:
    app.kubernetes.io/name: backend
spec: 
  selector:
    matchLabels:
      app.kubernetes.io/name: loginapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loginapi
    spec:
      containers:
        - name: loginapi
          image: ghcr.io/vchen7629/loginapi
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests: 
              cpu: 500m
              memory: 256Mi
          env:
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-db-app
                  key: host
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-db-app
                  key: port
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-db-app
                  key: user
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-db-app
                  key: password
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-db-app
                  key: dbname
            - name: Redis_Password
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: Redis_Addr
              value: redis-master.backend.svc.cluster.local:5432
            - name: Redis_DB
              value: "0"
