apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyphria-loginapi-deployment
  labels:
    app.kubernetes.io/name: loginapi
spec: 
  selector:
    matchLabels:
      app.kubernetes.io/name: loginapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loginapi
    spec:
      containers:
        - name: cyphria-frontend
          image: ghcr.io/vchen7629/loginapi
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests: 
              cpu: 125m
              memory: 256Mi
