apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyphria-loginapi-deployment
  labels:
    app.kubernetes.io/name: backend
spec: 
  selector:
    matchLabels:
      app.kubernetes.io/name: loginapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loginapi
    spec:
      containers:
        - name: loginapi
          image: ghcr.io/vchen7629/loginapi
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests: 
              cpu: 125m
              memory: 256Mi
          env:
            - name: PG_HOST
              valuesFrom:
                secretKeyRef:
                  name: postgres-db-app
                  key: host
            - name: PG_PORT
              valuesFrom:
                secretKeyRef:
                  name: postgres-db-app
                  key: port
            - name: PG_USER
              valuesFrom:
                secretKeyRef:
                  name: postgres-db-app
                  key: user
            - name: PG_PASS
              valuesFrom:
                secretKeyRef:
                  name: postgres-db-app
                  key: pgpass
            - name: PG_DB
              valuesFrom:
                secretKeyRef:
                  name: postgres-db-app
                  key: dbname
