apiVersion: v1
kind: Service
metadata:
  name: loginapi-service
  namespace: loginapi
spec: 
  type: ClusterIP
  selector: 
    app.kubernetes.io/name: loginapi
  ports:
    - port: 449
      targetPort: 3000
      protocol: TCP
      name: http
