apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyphria-frontend-deployment
  labels:
    app.kubernetes.io/name: frontend
spec: 
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
        - name: cyphria-frontend
          image: ghcr.io/vchen7629/cyphria-frontend
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests: 
              cpu: 128m
              memory: 256Mi
