- name: Uninstall Cert manager in argocd
  kubernetes.core.k8s:
    api_version: argoproj.io/v1alpha1
    state: absent
    kind: Application
    name: cert-manager
    namespace: argocd

- name: Delete Cluster Issuer
  ansible.builtin.command:
    cmd: kubectl delete clusterissuer letsencrypt-dns

- name: Delete Certificate
  ansible.builtin.command:
    cmd: kubectl delete certificate tls -n cert-manager
