apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: external-dns 
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: v1.16.1

    helm: 
      valuesObject:
        sources:
          - ingress
        policy: sync
        provider:
          name: cloudflare
        env: 
        - name: CF_API_TOKEN
          valueFrom: 
            secretKeyRef:
              name: cloudflare-api-key
              key: apiKey
        service:
          enabled: true


  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
