apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  creationTimestamp: "2025-04-30T03:02:34Z"
  generation: 1
  name: default
  namespace: argocd
  resourceVersion: "1816"
  uid: a64bf16f-636f-4f89-904a-fb3760cef5d2
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
status: {}
