- name: Validate Role
  ansible.builtin.import_tasks:
    file: validation.yaml
  any_errors_fatal: true

- name: Role Provisioning
  block:
    - name: install k3s binary
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3-installer.sh
        owner: root
        group: root
        mode: '755'
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: execute binary
      ansible.builtin.shell: sh /tmp/k3-installer.sh
      args: 
        chdir: /tmp/

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: role configuration
  ansible.builtin.import_tasks:
    file: configuration.yaml

- name: Server configuration
  notify: Restart Service
  block:
    - name: finish role postinitialization
      ansible.builtin.set_fact:
        k3s_postinstall: true
      
    - name: set server config file
      ansible.builtin.template:
        src: config.j2
        dest: ../../etc/systemd/system/k3s.service
        owner: root
        group: root
        mode: '600'
      
      
  