- name: Deploy helm chart to argocd
  block:
    - name: Create nginx monitor namespace
      kubernetes.core.k8s:
        name: ingress-nginx-monitor
        state: present 
        kind: Namespace
        api_version: v1

    - name: Apply ArgoCD manifest for ingress nginx
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'argocd.yaml') | from_yaml }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml
      register: result
      
    - name: Show apply result
      debug:
        var: result.result | default(result)