- name: Configure namespaces
  ansible.builtin.import_tasks:
    file: namespaces.yaml
  any_errors_fatal: true


- name: Configure Network Policies
  block:    
    - name: Apply Argocd Server Network Policy
      ansible.builtin.shell:
        cmd: "calicoctl apply -f -"
        stdin: "{{ lookup('file', item) }}"
      with_items:
        - "{{ playbook_dir }}/cluster_roles/network-policies/argocd/server.yaml" 
        - "{{ playbook_dir }}/cluster_roles/network-policies/argocd/repo-server.yaml"
        - "{{ playbook_dir }}/cluster_roles/network-policies/argocd/redis.yaml"
        - "{{ playbook_dir }}/cluster_roles/network-policies/argocd/dex-server.yaml"
        - "{{ playbook_dir }}/cluster_roles/network-policies/argocd/applicationset-controller.yaml"
        - "{{ playbook_dir }}/cluster_roles/network-policies/argocd/application-controller.yaml"
      register: result
      retries: 3
      delay: 1
      until: result is not failed
  
    - name: Apply ingress nginx network Policy
      ansible.builtin.shell:
        cmd: "calicoctl apply -f -"
        stdin: "{{ lookup('file', item) }}"
      with_items:
        - "{{ playbook_dir }}/cluster_roles/network-policies/deployed-applications/nginx.yaml"
        - "{{ playbook_dir }}/cluster_roles/network-policies/deployed-applications/prometheus-operator.yaml"
        - "{{ playbook_dir }}/cluster_roles/network-policies/deployed-applications/frontend.yaml" 
        - "{{ playbook_dir }}/cluster_roles/network-policies/deployed-applications/cloudflare-tunnel.yaml"
        - "{{ playbook_dir }}/cluster_roles/network-policies/deployed-applications/external-dns.yaml"
        - "{{ playbook_dir }}/cluster_roles/network-policies/deployed-applications/cert-manager.yaml"
      register: result
      retries: 3
      delay: 1
      until: result is not failed    
    
    - name: Apply default deny all Policy
      ansible.builtin.shell: 
        cmd: "calicoctl create -f -"
        stdin: "{{ lookup('file', playbook_dir + '/cluster_roles/network-policies/general/deny-all.yaml') }}"
    
    
          

        