FROM python:3.13-slim

WORKDIR /app

# create non-root user
RUN groupadd -r appuser && useradd -r -g appuser appuser 

# Copy shared package first
COPY shared/ ./shared/

ENV TRANSFORMERS_CACHE=/app/.cache/transformers
ENV HF_HOME=/app/.cache/huggingface

# install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY data_pipeline/sentiment_analysis/pyproject.toml data_pipeline/sentiment_analysis/uv.lock ./

# For installing dependencies
RUN data_pipeline/sentiment_analysis/uv sync --frozen --no-dev

RUN mkdir -p /app/.cache && \
    uv run python -c "from transformers import AutoTokenizer, AutoModelForSequenceClassification; print('Downloading model and tokenizer'); \
    AutoTokenizer.from_pretrained('yangheng/deberta-v3-base-absa-v1.1'); \
    AutoModelForSequenceClassification.from_pretrained('yangheng/deberta-v3-base-absa-v1.1'); \
    print('Model downloaded.')"

COPY src/ ./

RUN chown -R appuser:appuser /app

USER appuser

# Healthcheck to check to see if container fails
HEALTHCHECK --interval=30s --timeout=10s --start-period=1m --retries=3 \
  CMD pgrep -f "uvicorn" > /dev/null || exit 1

EXPOSE 8000

CMD ["uv", "run", "uvicorn", "src.fastapi_entry_point:app", "--host", "0.0.0.0", "--port", "8000"]