argocd_vars:
  kubernetes:
    helm:
      chart:  
        name: argo-cd
        version: v7.8.26
      repository:
        name: argo-helm
        org: argoproj
        url: https://argoproj.github.io
    namespace: argocd
    controller:
      replicas: 1
      resources:
        limits:
          cpu: null
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
    dex: 
      resources:
        limits: 
          cpu: null
          memory: 128Mi
        requests: 
          cpu: 10m
          memory: 128Mi
    redis:
      ha:
        enabled: false # turn this on if we have 3+ worker nodes
      resources:
        limits: 
          cpu: null
          memory: 128Mi
        requests: 
          cpu: 10m
          memory: 128Mi
    repo_server:
      autoscaling: 
        enabled: true
        min_replicas: 1
        max_replicas: 3
        target: 
          utilization_percentage:
            cpu: null
            memory: 80
      resources:
        limits:
          cpu: null
          memory: 512Mi
        requests: 
          cpu: 10m
          memory: 256Mi
    server: 
      autoscaling:
        enabled: true
        min_replicas: 1
        max_replicas: 3
        target: 
          utilization_percentage:
            cpu: null
            memory: 80
      credentials:
        admin:
          password: testing
        user: 
          name: zephyrus
          password: 5526
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests: 
          cpu: 10m
          memory: 128Mi

  kubeconfig:
    path: /etc/rancher/k3s/k3s.yaml
  release: 
    checksum: cli_checksums.txt
    file: argocd-linux-amd64
    repository:
      name: argo-cd
      org: argoproj
    version: v2.14.10