apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kminion-pod-monitor
  namespace: prometheus
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kminion
      app.kubernetes.io/instance: kafka-metrics
  namespaceSelector:
    matchNames:
      - kafka
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s

