- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yml
  any_errors_fatal: true

- name: Cluster Provisioning
  block:
    - name: cluster configuration
      ansible.builtin.import_tasks:
        file: configuration.yml
    
    - name: upgrade cluster
      ansible.builtin.import_tasks:
        file: upgrade.yml

- name: flush handlers
  ansible.builtin.meta: flush_handlers