---
metricsserver_vars:
  kubernetes:
    helm:
      chart:
        name: metrics-server
        version: v3.13.0
      repository:
        name: metrics-server
        org: kubernetes-sigs
        url: https://kubernetes-sigs.github.io
    namespace: kube-system
    replicas: 1
    resources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
    server:
      args:
        - --v=1
      tls:
        type: metrics-server