apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: timescaledb-weekly-backup
spec:
  schedule: "0 0 3 * * 0"
  backupOwnerReference: cluster
  cluster:
    name: timescaledb-cluster-pg17