apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: prometheus-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: prometheus-operator-crds
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: v19.0.0

    helm:
      valuesObject:
        crds:
          alertmanagerconfigs:
            enabled: false
          
          alertmanagers:
            enabled: false
          
          prometheusagents:
            enabled: false
          
          prometheuses:
            enabled: false

          scrapeconfigs:
            enabled: false
          
          thanosrulers:
            enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true