# Auth users to secure the kafka cluster so only allowed services can
# produce and consume from allowed topics

# data ingestion user
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: data-ingestion-user
  namespace: kafka
  labels:
    strimzi.io/cluster: cyphria-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Allows producing messages to raw-topic
      - resource:
          type: topic
          name: raw-topic
          patternType: literal
        operations:
          - Describe
          - Create
          - Write
        host: "*"

      # Allows producing messages to raw-topic dlq
      - resource:
          type: topic
          name: raw-topic-dlq
          patternType: literal
        operations:
          - Describe
          - Create
          - Write
        host: "*"

# category classification user
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: category-classification-user
  namespace: kafka
  labels:
    strimzi.io/cluster: cyphria-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Allows producing messages to aggregated
      - resource:
          type: topic
          name: aggregated
          patternType: literal
        operations:
          - Describe
          - Create
          - Write
        host: "*"
      # Allows producing messages to aggregated dlq
      - resource:
          type: topic
          name: aggregated-dlq
          patternType: literal
        operations:
          - Describe
          - Create
          - Write
        host: "*"
      # Allows consuming from sentence-embeddings topic
      - resource:
          type: topic
          name: sentence-embeddings
          patternType: literal
        operations:
          - Describe
          - Create
          - Write
        host: "*"
      # consumer group defined in service code
      - resource:
          type: group
          name: category-classifier-service
          patternType: literal
        operations:
          - Read

# post embeddings user
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: post-embeddings-user
  namespace: kafka
  labels:
    strimzi.io/cluster: cyphria-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Allows producing messages to sentence-embeddings
      - resource:
          type: topic
          name: sentence-embeddings
          patternType: literal
        operations:
          - Describe
          - Create
          - Write
        host: "*"
      # Allows producing messages to sentence-embeddings dlq
      - resource:
          type: topic
          name: sentence-embeddings-dlq
          patternType: literal
        operations:
          - Describe
          - Create
          - Write
        host: "*"
      # Allows consuming from raw data topic
      - resource:
          type: topic
          name: raw-data
          patternType: literal
        operations:
          - Describe
          - Create
          - Write
        host: "*"
      # consumer group defined in service code
      - resource:
          type: group
          name: sentence-embeddings-service
          patternType: literal
        operations:
          - Read

# sentiment analysis user
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: sentiment-analysis-user
  namespace: kafka
  labels:
    strimzi.io/cluster: cyphria-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Allows producing messages to aggregated
      - resource:
          type: topic
          name: aggregated
          patternType: literal
        operations:
          - Describe
          - Create
          - Write
        host: "*"
      # Allows producing messages to aggregated dlq
      - resource:
          type: topic
          name: aggregated-dlq
          patternType: literal
        operations:
          - Describe
          - Create
          - Write
        host: "*"
      # Allows consuming from topic-classified topic
      - resource:
          type: topic
          name: topic-classified
          patternType: literal
        operations:
          - Describe
          - Create
          - Write
        host: "*"
      # consumer group defined in service code
      - resource:
          type: group
          name: sentiment-analysis-service
          patternType: literal
        operations:
          - Read

# topic classification user
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: topic-classification-user
  namespace: kafka
  labels:
    strimzi.io/cluster: cyphria-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Allows producing messages to topic-classified
      - resource:
          type: topic
          name: topic-classified
          patternType: literal
        operations:
          - Describe
          - Create
          - Write
        host: "*"
      # Allows producing messages to topic-classified dlq
      - resource:
          type: topic
          name: topic-classified-dlq
          patternType: literal
        operations:
          - Describe
          - Create
          - Write
        host: "*"
      # Allows consuming from sentence-embeddings topic
      - resource:
          type: topic
          name: sentence-embeddings
          patternType: literal
        operations:
          - Describe
          - Create
          - Write
        host: "*"
      # consumer group defined in service code
      - resource:
          type: group
          name: keyword-extraction-service
          patternType: literal
        operations:
          - Read