apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cyphria-cluster
  namespace: kafka
spec:
  kafka:
    version: 4.1.0
    metadataVersion: 4.1-IV1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      auto.create.topics.enable: false
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 2
      default.replication.factor: 2
      min.insync.replicas: 1

  kafkaExporter:
    groupRegex: ".*"
    topicRegex: ".*"
    template: {}

  entityOperator:
    topicOperator: {}
    userOperator: {}