# Topic containing the raw reddit data (unprocessed)
# with subreddit, post text, timestamp, post id
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: raw-data
  namespace: kafka
  labels:
    # cluster name that the topics are in
    strimzi.io/cluster: cyphria-cluster
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 28800000 # 8 hours
    segment.bytes: 1073741824

# DLQ Topic for raw reddit data
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: raw-data-dlq
  namespace: kafka
  labels:
    # cluster name that the topics are in
    strimzi.io/cluster: cyphria-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 86400000 # 1 day
    segment.bytes: 1073741824

# Topic containing the sentence embeddings of
# the post corresponding extracted using bert
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sentence-embeddings
  namespace: kafka
  labels:
    # cluster name that the topics are in
    strimzi.io/cluster: cyphria-cluster
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 28800000 # 8 hours
    segment.bytes: 1073741824

# DLQ for sentence embeddings topic
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sentence-embeddings-dlq
  namespace: kafka
  labels:
    # cluster name that the topics are in
    strimzi.io/cluster: cyphria-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 86400000 # 1 day
    segment.bytes: 1073741824
  
# Topic containing the topics classified of
# the post corresponding to the post id
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: topic-classified
  namespace: kafka
  labels:
    # cluster name that the topics are in
    strimzi.io/cluster: cyphria-cluster
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 28800000 # 8 hours
    segment.bytes: 1073741824

# DLQ for topics classified topic
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: topic-classified-dlq
  namespace: kafka
  labels:
    # cluster name that the topics are in
    strimzi.io/cluster: cyphria-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 86400000 # 1 day
    segment.bytes: 1073741824

# Topic containing the combined sentiments, category of
# the post to be combined into one
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: aggregated
  namespace: kafka
  labels:
    # cluster name that the topics are in
    strimzi.io/cluster: cyphria-cluster
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 28800000 # 8 hours
    segment.bytes: 1073741824

# DLQ for combined posts topic
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: aggregated-dlq
  namespace: kafka
  labels:
    # cluster name that the topics are in
    strimzi.io/cluster: cyphria-cluster
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 86400000 # 1 day
    segment.bytes: 1073741824
