- name: setting up map facts
  ansible.builtin.set_fact:
    k3s_map:
      agent:
        ha: '{{ groups.agent | length > 2 }}'
        hosts: '{{ groups.agent }}'
      cluster:
        dns: 10.43.0.10
        label: default
      node:
        default_registry_endpoint:
          enabled: true
        directory:
          bin: /usr/local/bin
          config: /etc/rancher/k3s
          data: /var/lib/rancher/k3s
        kubelet:
          eviction_hard:
            memory_available: 500Mi # evict pods on node if only 500 Mi ram left
          eviction_max_pod_grace_period: 60
          eviction_soft:
            memory_available: 1Gi
          system_reserved:
            cpu: 1000m
            ephemeral_storage: 5Gi
            memory: 1Gi
        sysctl_parameters:
          fs.file-max: 1048576
          fs.inotify.max_user_watches: 262144
          fs.inotify.max_user_instances: 256
          kernel.panic: 10
          kernel.panic_on_oops: 1
          net.core.bpf_jit_kallsyms: 1
          net.core.default_qdisc: fq
          net.core.netdev_max_backlog: 8192
          net.core.optmem_max: 262144
          net.core.somaxconn: 8192
          net.core.rmem_max: 8388608
          net.core.wmem_max: 8388608
          net.ipv4.ip_nonlocal_bind: 1
          net.ipv4.ip_forward: 1
          net.ipv4.ip_local_port_range: 1024 65535
          net.ipv4.neigh.default.gc_thresh1: 4096
          net.ipv4.neigh.default.gc_thresh2: 8192
          net.ipv4.neigh.default.gc_thresh3: 16384
          net.ipv4.tcp_congestion_control: bbr
          net.ipv4.tcp_fin_timeout: 30
          net.ipv4.tcp_keepalive_time: 600
          net.ipv4.tcp_keepalive_intvl: 30
          net.ipv4.tcp_keepalive_probes: 10
          net.ipv4.tcp_max_syn_backlog: 8192
          net.ipv4.tcp_rmem: 4096 6291456 8388608
          net.ipv4.tcp_wmem: 4096 6291456 8388608
          net.ipv4.tcp_tw_reuse: 1
          net.ipv6.conf.all.forwarding: 1
          net.netfilter.nf_conntrack_buckets: 262144
          net.netfilter.nf_conntrack_max: 262144
          net.netfilter.nf_conntrack_tcp_timeout_established: 86400
          vm.dirty_background_ratio: 5
          vm.dirty_ratio: 10
          vm.max_map_count: 262144
          vm.min_free_kbytes: 131072
          vm.overcommit_memory: 1
          vm.swappiness: 1
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
      server: # this is from the hosts.yaml file in inventory folder
        default_host: '{{ hostvars[groups.server[0]].hosts.ansible_hostname | default(groups.server[0]) }}'
        ha: '{{ groups.server | length > 2 }}'
        hosts: '{{ groups.server }}'
        non_ha: '{{ groups.server | length == 1}}'
      service:
        name: "k3s{{ '-agent' if inventory_hostname not in groups.server }}"
  run_once: true

- name: set project fact
  ansible.builtin.set_fact:
    k3s_project:
      cluster:
        config: '{{ k3s_map.node.directory.config }}/config.yaml'
        token: "{{ hostvars[k3s_map.server.default_host].k3s_project.cluster.token | default('') }}"
        tolerations: ""
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        config_kubelet: '/etc/rancher/k3s/kubelet.yaml'
      node:
        binary: /usr/local/bin/k3s
      release:
        kubepug: 
          checksum: 'https://github.com/kubepug/kubepug/releases/download/v1.7.1/kubepug_1.7.1_checksums.txt'
          file: 'https://github.com/kubepug/kubepug/releases/download/v1.7.1/kubepug_linux_amd64.tar.gz'

- name: Set Node fact
  ansible.builtin.set_fact:
    k3s_node:
      ip: '{{ ansible_default_ipv4.address }}'
      binary: '{{ k3s_map.node.directory.bin }}/k3s'
      service: 
        name: "{{ 'agent' if inventory_hostname not in k3s_map.server.hosts else 'server' }}"
        type: "{{ 'agent' if inventory_hostname not in groups.server else 'server' }}"


- name: Set variables fact
  ansible.builtin.set_fact:
    k3s_vars: '{{ k3s_vars }}'
  run_once: true