apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-db-ca
  namespace: postgres
spec:
  commonName: postgres
  secretName: postgres-ca-secret
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer