[project]
name = "sentence-embeddings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "confluent-kafka>=2.12.0",
    "sentence-transformers>=5.1.1",
]
