- name: Restart service
  ansible.builtin.systemd_service:
    name: '{{ k3s_map.service.name }}.service'
    state: restarted
    daemon_reload: true
    enabled: true

- name: Restart Sysctl
  ansible.builtin.command:
    cmd: sysctl --system
  changed_when: false

- name: Reboot
  ansible.builtin.reboot: