apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Vchen7629/Cyphria.git
    targetRevision: main
    path: infrastructure/kubernetes/roles/prometheus/overlay

  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus 

  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true