- name: Include tunnel facts variables
  ansible.builtin.include_vars:
    file: "../roles/cloudflare_tunnel/credentials/temp.yaml"
    
- name: Deploy frontend
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'argo-cd-deployment.yaml') | from_yaml }}"
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Deploy frontend Ingress
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'ingress-service.j2') | from_yaml }}"
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  register: result
  retries: 20
  delay: 15
  until: result is not failed
