apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-service-monitor
  namespace: prometheus
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: argo-cd
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
    - port: metrics
      path: /metrics # argocd application controller metrics
      interval: 30s
      
