apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-service-monitor
  namespace: prometheus
  labels:
    release: prometheus
spec: 
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx
  namespaceSelector:
    matchNames: 
      - nginx
  endpoints:
    - port: metrics # nginx ingress metrics
      path: /metrics
      interval: 30s