- name: OS configuration
  block:
    - name: get host fqdn
      ansible.builtin.command:
        cmd: hostname --fqdn
      changed_when: false
      register: host_fqdn

    - name: get all host fqdns
      ansible.builtin.command:
        cmd: hostname --all-fqdns
      changed_when: false
      register: host_all_fqdns
    
    - name: set host facts
      ansible.builtin.set_fact:
        cluster_host: 
          extension: "{{ host_all_fqdns.stdout | split | first | split('.') | last | default('local') }}"
          fqdn: "{{ host_fqdn.stdout | split | first }}"
          ipv4: "{{ ansible_default_ipv4['address'] }}"
          name: "{{ ansible_host }}"
    
    - name: set host fqdn
      ansible.builtin.replace:
        path: /etc/hosts
        regexp: ^127.0.1.1\s.+\s{{ cluster_host['name'] }}$
        replace: 127.0.0.1 {{ cluster_host['fqdn'] }} {{ cluster_host['name'] }}
      notify: Reboot
      when: host_fqdn.stdout != cluster_host['fqdn']
    
    - name: Set root full name
      ansible.builtin.command:
        cmd: chfn -f "{{ cluster_host['name'] }}" root
      changed_when: false

    - name: Disable access time updates
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: defaults\t0
        replace: defaults,noatime\t0
      notify: Reboot

    - name: disable cloud-init service
      ansible.builtin.file:
        path: /etc/cloud/cloud-init.disabled
        access_time: preserve
        modification_time: preserve
        state: touch
        owner: root
        group: root
        mode: '700'
      notify: Reboot   

    - name: disable firewall
      ansible.builtin.systemd_service:
        name: ufw.service
        state: stopped
        enabled: false

    - name: disable snapd services
      ansible.builtin.systemd_service:
        name: '{{ item }}'
        state: stopped
        enabled: false
      loop:
        - snapd.apparmor.service
        - snapd.service
        - snapd.seeded.service
        - snapd.socket

    - name: load kernel modules for kubernetes
      ansible.builtin.copy:
        content: |
          - br_netfilter
          - overlay
        dest: /etc/modules-load.d/kubernetes.conf
        owner: root
        group: root
        mode: '644'
      notify: Reboot