
services:
  prometheus:
    image: prom/prometheus:latest
    tty: true
    stdin_open: true
    ports:
      - "9090:9090" 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: on-failure
    networks:
      monitoring:
        aliases:
          - prometheus
  grafana:
    depends_on: 
      - prometheus
    image: grafana/grafana:latest
    tty: true
    stdin_open: true
    ports: 
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SERVICE_ACCOUNTS_ENABLED=true
    restart: on-failure
    networks:
      monitoring:
        aliases:
          - grafana

volumes:
  grafana-storage:
  
networks:
  monitoring:
    name: monitoring