global:
  scrape_interval: "30s"
  
scrape_configs:
  - job_name: Apache Spark
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:4041']
    relabel_configs:
      - source_labels: []
        target_label: job_id
        replacement: 'Spark-driver'
      - target_label: job
        replacement: 'spark-driver-local'