- name: Reset Cluster - Server Apps
  hosts: server
  become: true
  gather_facts: true
  tasks:
    - name: Get packages information
      ansible.builtin.package_facts:

    - name: Reset application roles
      ansible.builtin.include_role:
        name: "{{ reset }}"
        tasks_from: reset
      loop:
        #- network_policies
        #- prometheus
        #- cert_manager
        #- nginx
        #- cloudflare_tunnel
        #- external_dns
        #- frontend
        #- metrics_server
        #- argo_cd
        - cilium
      loop_control:
        loop_var: reset
    
    - name: Reset cluster roles
      ansible.builtin.include_role:
        name: "{{ reset }}"
        tasks_from: reset
      loop:
        - cluster
        - k3s
      loop_control:
        loop_var: reset

- name: Reset Cluster - Agent
  hosts: agent
  become: true
  gather_facts: true
  tasks:
    - name: Get packages information
      ansible.builtin.package_facts:
      
    - name: Reset cluster roles
      ansible.builtin.include_role:
        name: "{{ reset }}"
        tasks_from: reset
      loop:
        - cluster
        - k3s
      loop_control:
        loop_var: reset

- name: Post Tasks
  hosts: cluster
  become: true
  gather_facts: false
  tasks:
    - name: Remove archived journal files
      ansible.builtin.command:
        cmd: journalctl --rotate --vacuum-time=1m30s
      changed_when: false
