- name: Reset Cluster
  hosts: cluster
  become: true
  gather_facts: true
  serial:
    - 3
    - 5
  post_tasks:
    - name: remove archived journal files
      ansible.builtin.command:
        cmd: journalctl --rotate --vacuum-time=1m30s
      changed_when: false
  tasks:
    - name: Get packages information
      ansible.builtin.package_facts:
      tags: always

    - name: Reset cluster
      ansible.builtin.include_role:
        apply:
          tags: '{{ reset }}'
        name: '{{ reset }}'
        tasks_from: reset
      loop:
        - network_policies
        - cert_manager
        - prometheus
        - nginx
        - cloudflare_tunnel
        - external_dns
        - frontend
        - argo_cd
        - calico
        - cluster
        - k3s
      loop_control:
        loop_var: reset
      tags: always
      when: (ansible_run_tags == ['all']) or (reset in ansible_run_tags)
  vars_prompt:
    - name: prompt_remove_packages
      prompt: Remove installed apt packages? [Y/n]
      default: 'n'
      private: false