- name: Reset Cluster
  hosts: server
  become: true
  serial:
    - 3
    - 5
  tasks:
  - name: Reset cluster
    ansible.builtin.include_role:
      apply:
        tags: '{{ reset }}'
      name: '{{ reset }}'
      tasks_from: reset
    loop:
      #- network_policies
      #- cert_manager
      - argo_cd
      - prometheus
      #- nginx
      #- cloudflare_tunnel
      #- external_dns
      #- frontend
      #- argo_cd
      #- calico
    loop_control:
      loop_var: reset
      