services:
  testing-postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "account"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
  
  redis-insight:
    image: redislabs/redisinsight:latest 
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/db
volumes:
  redisinsight_data: