FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o myapp

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/myapp .

EXPOSE 3000

ENTRYPOINT [ "go", "run", "main.go" ]