- name: Uninstall prometheus crds in argocd
  kubernetes.core.k8s:
    api_version: argoproj.io/v1alpha1
    state: absent
    kind: Application
    name: prometheus-operator-crds
    namespace: argocd

- name: Uninstall prometheus operator in argocd
  kubernetes.core.k8s:
    api_version: argoproj.io/v1alpha1
    state: absent
    kind: Application
    name: prometheus-operator
    namespace: argocd

