- name: Apply ArgoCD manifest for ingress nginx
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'argocd.yaml') | from_yaml }}"
    kubeconfig: /etc/rancher/k3s/k3s.yaml