apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: Cyphria
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.17.1 

    helm: 
      valueFiles:
        - values.j2

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

syncPolicy:
  syncOptions:
    - CreateNamespace=true
