apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: argocd-applicationset-controller-network-policy
  namespace: argocd
spec:
  order: 80
  selector: app.kubernetes.io/name == "argocd-applicationset-controller"
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow # exposing ArgoCD applicationset controller metrics endpoint
      protocol: TCP
      destination:
        namespaceSelector: projectcalico.org/name == "prometheus"
        selector: app.kubernetes.io/instance == "prometheus-operator"
        ports: [8080]
  egress:
    - action: Allow # Allowing ArgoCD applicationset -> ArgoCD repo server for template processing
      protocol: TCP
      destination:
        selector: app.kubernetes.io/name == "argocd-repo-server"
        ports: [8081]