FROM python:3.13-alpine

WORKDIR /app

# install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# for dependency files
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

# for source code
COPY src/* ./src/

EXPOSE 8000

CMD ["uv", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]