
- name: Role Reset
  block:
    - name: Remove Repo
      kubernetes.core.helm_repository:
        name: '{{ calico_vars.kubernetes.helm.repository.org }}'
        repo_state: absent
    
    - name: Remove calicoctl
      ansible.builtin.file:
        path: /usr/local/bin/calicoctl
        state: absent
    
    - name: Remove services
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml
      with_items: 
        - felix-metrics.j2
        - typha-metrics.j2