apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: frontend
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: cyphria-frontend-deployment
  min_replicas: 1
  max_replicas: 6
  metrics:
    - type: Resource
      resource:
        name: memory
        target: 
          type: AverageValue
          averageValue: 750Mi