apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyphria-frontend-deployment
  labels:
    app.kubernetes.io/name: frontend
spec: 
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
        - name: cyphria-frontend
          image: ghcr.io/vchen7629/cyphria-frontend:latest
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests: 
              cpu: 100m
              memory: 800Mi
