- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - cert_manager
    - external_dns
    - k3s
    - cilium
  loop_control:
    loop_var: role

- name: Role Validation
  when: (ansible_run_tags in [(), ('all',)]) or ('cilium' in ansible_run_tags)
  run_once: true
  block:
    - name: Validate project url
      ansible.builtin.uri:
        url: '{{ cilium_project.url }}/{{ cilium_project.tag }}'
        timeout: 5
      run_once: true
      register: cilium_result
      delay: 1
      retries: 3
      until: cilium_result is not failed

    - name: Validate cli release file url
      ansible.builtin.uri:
        url: '{{ cilium_project.release.cli.url }}/{{ cilium_project.release.cli.file }}'
        timeout: 5
      run_once: true
      register: cilium_result
      delay: 1
      retries: 3
      until: cilium_result is not failed

    - name: Validate gateway-api release file url
      ansible.builtin.uri:
        url: '{{ cilium_project.release.gateway_api.url }}/{{ cilium_project.release.gateway_api.file }}'
        timeout: 5
      run_once: true
      register: cilium_result
      delay: 1
      retries: 3
      until: cilium_result is not failed
    
    - name: Chart Validation
      block:
        - name: Update repository
          kubernetes.core.helm_repository:
            name: '{{ cilium_vars.kubernetes.helm.repository.org }}'
            repo_url: '{{ cilium_map.helm.repository.url }}'
            force_update: true
        
        - name: Validate cluster kubeconfig path
          ansible.builtin.stat:
            path: '{{ k3s_project.cluster.kubeconfig }}'
          register: cilium_kubeconfig
          changed_when: false
        
        - name: Get deployed chart release info
          kubernetes.core.helm_info:
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            name: '{{ cilium_vars.kubernetes.helm.chart.name }}'
            namespace: '{{ cilium_vars.kubernetes.namespace }}'
          register: cilium_release
          when: cilium_kubeconfig.stat.exists
          changed_when: false
        
        - name: Set comparison fact
          ansible.builtin.set_fact:
            cilium_comparison:
              chart: '{{ cilium_vars.kubernetes.helm.chart.version[1:] }}'
              release: "{{ cilium_release.status.chart | default('0') | regex_search('[0-9.]+') }}"
        
        - name: Validate gateway values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'gateway.j2') }}"
        
        - name: Set chart setup fact
          ansible.builtin.set_fact:
            cilium_setup: true
        
        - name: Set chart postinstall fact
          ansible.builtin.set_fact:
            cilium_postinstall: false
        
        - name: Validate setup chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Set chart values fact
          ansible.builtin.set_fact:
            cilium_chart_values: "{{ lookup('ansible.builtin.template', 'values.j2') | trim | from_yaml }}"

        - name: Update chart setup fact
          ansible.builtin.set_fact:
            cilium_setup: false

        - name: Validate post-setup chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"