

- name: Delete Nginx Operator Deployment
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: Deployment
    name: nginx-ingress-nginx-controller
    namespace: nginx


- name: Delete Nginx Services
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    name: "{{ item }}"
    namespace: nginx
  loop:
    - nginx-ingress-nginx-controller
    - nginx-ingress-nginx-controller-metrics
    - nginx-ingress-nginx-controller-admission
  ignore_errors: true

- name: Uninstall nginx application in argocd
  kubernetes.core.k8s:
    api_version: argoproj.io/v1alpha1
    state: absent
    kind: Application
    name: nginx
    namespace: argocd
  

- name: Delete Nginx Issuer resourcs
  ansible.builtin.command:
    cmd: "{{ certificate_resource }}"
  loop:
    - kubectl delete issuer nginx-ingress-nginx-root-issuer -n nginx
    - kubectl delete issuer nginx-ingress-nginx-self-signed-issuer -n nginx
  loop_control:
    loop_var: certificate_resource
  ignore_errors: true
  

- name: Delete Nginx Certificate resourcs
  ansible.builtin.command:
    cmd: "{{ certificate_resource }}"
  loop:
    - kubectl delete certificate nginx-ingress-nginx-admission -n nginx
    - kubectl delete certificate nginx-ingress-nginx-root-cert -n nginx
    - kubectl delete secrets nginx-ingress-nginx-admission -n nginx
    - kubectl delete secrets nginx-ingress-nginx-root-cert -n nginx
  loop_control:
    loop_var: certificate_resource
  ignore_errors: true
