
- name: OS configuration
  hosts: cluster
  become: true
  gather_facts: true
  roles:
    - cluster
  tags: cluster

#- name: Provision Load Balancer
#  hosts: cluster
#  become: true
#  gather_facts: true

- name: k3s Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  roles: 
    - k3s
    - helm
  serial:
    - 1
    - 2
    - 5
  tags: kubernetes

- name: Core Application Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  roles: 
    - calico
    - argo-cd
  tags: charts

- name: ArgoCD deployed applications provisioning
  hosts: cluster
  become: true
  roles: 
    #- network-policies
    - prometheus
    - nginx
    - cloudflare-tunnel
    - external-dns
    - frontend
  tags: charts