
- name: OS configuration
  hosts: cluster
  become: true
  gather_facts: true
  roles:
    - cluster
  tags: cluster

#- name: Provision Load Balancer
#  hosts: cluster
#  become: true
#  gather_facts: true

- name: k3s Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  roles: 
    - k3s
    - helm
  serial:
    - 1
    - 2
    - 5
  tags: kubernetes

- name: Application Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  post_tasks:
    - name: post install tasks
      ansible.builtin.include_role:
        name: "{{ postinstall }}"
        tasks_from: postinstall
      loop: 
        - argo-cd
      loop_control:
        loop_var: postinstall
  roles: 
    - calico
    - argo-cd
    - network-policies
    - nginx
    - prometheus
    - frontend
  tags: charts
