- name: Deploy Secrets For DB
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  with_items: 
    - redis-secret.j2

- name: Deploy Login Api via ArgoCD
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'argocd-deployment.yaml') | from_yaml }}"