- name: Delete Login Api Deployment
  kubernetes.core.k8s:
    state: absent
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: login-api
    namespace: argocd

- name: Remove Secrets
  ansible.builtin.command:
    cmd: kubectl delete secrets redis-creds -n backend
