- name: Delete Login Api Deployment
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: Deployment
    name: loginapi
    namespace: argocd

- name: Remove Secrets
  ansible.builtin.command:
    cmd: kubectl delete secrets redis-creds -n backend
