FROM python:3.13-alpine

WORKDIR /app

# install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy shared package first
COPY shared/ ./shared/

# for dependency files
COPY data_pipeline/ranking_calculator/pyproject.toml data_pipeline/ranking_calculator/uv.lock ./
RUN uv sync --frozen --no-dev

# for source code
COPY data_pipeline/ranking_calculator/src/* ./src/

EXPOSE 8000

CMD ["uv", "run", "uvicorn", "src.fastapi_entry_point:app", "--host", "0.0.0.0", "--port", "8000"]