from src.product_mappings.computing import (
    CPU_MODEL_TO_BRAND,
    GPU_MODEL_TO_BRAND,
    LAPTOP_MODEL_TO_BRAND,
    MONITOR_MODEL_TO_BRAND,
    KEYBOARD_MODEL_TO_BRAND,
)
from src.product_mappings.audio import (
    DAC_MODEL_TO_BRAND,
    EARBUD_MODEL_TO_BRAND,
    SPEAKER_MODEL_TO_BRAND,
    HEADSET_MODEL_TO_BRAND,
    SOUNDBAR_MODEL_TO_BRAND,
    HEADPHONE_MODEL_TO_BRAND,
)
from src.product_mappings.mobile import (
    TABLET_MODEL_TO_BRAND,
    SMARTPHONE_MODEL_TO_BRAND,
)
from src.product_mappings.gaming import (
    CONTROLLER_MODEL_TO_BRAND,
    GAMING_MOUSE_MODEL_TO_BRAND,
    GAMING_LAPTOP_MODEL_TO_BRAND,
)

from src.product_mappings.photography import (
    CAMERA_MODEL_TO_BRAND,
    TRIPOD_MODEL_TO_BRAND,
    CAMERA_BACKPACK_MODEL_TO_BRAND,
)

from src.product_mappings.kitchen import (
    ESPRESSO_MACHINE_MODEL_TO_BRAND_MAPPINGS,
    AIRFRYER_MODEL_TO_BRAND_MAPPINGS,
    BLENDER_MODEL_TO_BRAND_MAPPING,
)

__all__ = [
    "CPU_MODEL_TO_BRAND",
    "GPU_MODEL_TO_BRAND",
    "LAPTOP_MODEL_TO_BRAND",
    "MONITOR_MODEL_TO_BRAND",
    "KEYBOARD_MODEL_TO_BRAND",
    "DAC_MODEL_TO_BRAND",
    "EARBUD_MODEL_TO_BRAND",
    "SPEAKER_MODEL_TO_BRAND",
    "SOUNDBAR_MODEL_TO_BRAND",
    "HEADPHONE_MODEL_TO_BRAND",
    "HEADSET_MODEL_TO_BRAND",
    "TABLET_MODEL_TO_BRAND",
    "SMARTPHONE_MODEL_TO_BRAND",
    "CONTROLLER_MODEL_TO_BRAND",
    "GAMING_MOUSE_MODEL_TO_BRAND",
    "GAMING_LAPTOP_MODEL_TO_BRAND",
    "CAMERA_MODEL_TO_BRAND",
    "TRIPOD_MODEL_TO_BRAND",
    "CAMERA_BACKPACK_MODEL_TO_BRAND",
    "ESPRESSO_MACHINE_MODEL_TO_BRAND_MAPPINGS",
    "AIRFRYER_MODEL_TO_BRAND_MAPPINGS",
    "BLENDER_MODEL_TO_BRAND_MAPPING",
]
