HEADPHONE_MODEL_TO_BRAND = {
    # AKG
    "K72": "AKG",
    "K92": "AKG",
    "K182": "AKG",
    "K240 MK2": "AKG",
    "K240 Studio": "AKG",
    "K361": "AKG",
    "K361-BT": "AKG",
    "K371": "AKG",
    "K371-BT": "AKG",
    "Lyra": "AKG",
    "Y500 Wireless": "AKG",
    # Apple
    "Airpods Max": "Apple",
    # Audeze
    "CRBN2": "Audeze",
    "LCD-MX4": "Audeze",
    "LCD-S20": "Audeze",
    "LCD-X": "Audeze",
    "LCD-XS": "Audeze",
    "LCD-2": "Audeze",
    "LCD-2 Classic": "Audeze",
    "LCD-3": "Audeze",
    "LCD-4z": "Audeze",
    "LCD-5s": "Audeze",
    "MM-100": "Audeze",
    "MM-500": "Audeze",
    # Audio-Technica
    "ATH-ADX3000": "Audio-Technica",
    "ATH-ADX5000": "Audio-Technica",
    "ATH-ADX7000": "Audio-Technica",
    "ATH-AD500X": "Audio-Technica",
    "ATH-AD700X": "Audio-Technica",
    "ATH-AD900X": "Audio-Technica",
    "ATH-AWAS": "Audio-Technica",
    "ATH-AWKG": "Audio-Technica",
    "ATH-AWKT": "Audio-Technica",
    "ATH-AVC200": "Audio-Technica",
    "ATH-AVC400": "Audio-Technica",
    "ATH-A550Z": "Audio-Technica",
    "ATH-A990Z": "Audio-Technica",
    "ATH-M20X": "Audio-Technica",
    "ATH-M20XBT": "Audio-Technica",
    "ATH-M30X": "Audio-Technica",
    "ATH-M40X": "Audio-Technica",
    "ATH-M50X": "Audio-Technica",
    "ATH-M50XBT2": "Audio-Technica",
    "ATH-M60XA": "Audio-Technica",
    "ATH-M70X": "Audio-Technica",
    "ATH-R30X": "Audio-Technica",
    "ATH-R50X": "Audio-Technica",
    "ATH-R70XA": "Audio-Technica",
    "ATH-S120C": "Audio-Technica",
    "ATH-S220BT": "Audio-Technica",
    "ATH-S300BT": "Audio-Technica",
    "ATH-WBLTD": "Audio-Technica",
    "ATH-WP900": "Audio-Technica",
    # Beats
    "Solo 4": "Beats",
    "Studio Pro": "Beats",
    # Beyerdynamic
    "Amiron Home": "Beyerdynamic",
    "Amiron Wireless": "Beyerdynamic",
    "Aventho 100": "Beyerdynamic",
    "Aventho 300": "Beyerdynamic",
    "BT 900 Pro X": "Beyerdynamic",
    "DT 100": "Beyerdynamic",
    "DT 150": "Beyerdynamic",
    "DT 1770 Pro Mk1": "Beyerdynamic",
    "DT 1770 Pro MK2": "Beyerdynamic",
    "DT 1990 Pro MK2": "Beyerdynamic",
    "DT 250": "Beyerdynamic",
    "DT 252": "Beyerdynamic",
    "DT 270 Pro": "Beyerdynamic",
    "DT 700 Pro X": "Beyerdynamic",
    "DT 770 M": "Beyerdynamic",
    "DT 770 Pro": "Beyerdynamic",
    "DT 770 Pro X": "Beyerdynamic",
    "DT 880": "Beyerdynamic",
    "DT 880 Pro": "Beyerdynamic",
    "DT 990": "Beyerdynamic",
    "DT 990 Pro": "Beyerdynamic",
    "DT 990 Pro X": "Beyerdynamic",
    "DJ 300 Pro X": "Beyerdynamic",
    "TYGR 300 R": "Beyerdynamic",
    # Bose
    "QuietComfort": "Bose",
    "QuietComfort Ultra": "Bose",
    # Focal
    "Azurys": "Focal",
    "Bathys": "Focal",
    "Bathys MG": "Focal",
    "Clear MG": "Focal",
    "Hadenys": "Focal",
    "Lensys": "Focal",
    "Utopia": "Focal",
    "Stellia": "Focal",
    # HIFIMAN
    "Ananda Nano": "HIFIMAN",
    "Ananda Stealth Magnet": "HIFIMAN",
    "Arya": "HIFIMAN",
    "Arya Organic": "HIFIMAN",
    "Audivinia": "HIFIMAN",
    "Edition XS": "HIFIMAN",
    "Edition X V2": "HIFIMAN",
    "HE-R10D": "HIFIMAN",
    "HE-R10P": "HIFIMAN",
    "HE-500": "HIFIMAN",
    "HE1000se": "HIFIMAN",
    "HE1000 Stealth": "HIFIMAN",
    "HE1000 V2": "HIFIMAN",
    "HE400i": "HIFIMAN",
    "HE5se": "HIFIMAN",
    "HE560": "HIFIMAN",
    "HE6": "HIFIMAN",
    "HE6se": "HIFIMAN",
    "ISVARNA": "HIFIMAN",
    "Jade II Electrostatic": "HIFIMAN",
    "Shangri-La": "HIFIMAN",
    "Shangri-La JR": "HIFIMAN",
    "Sundara": "HIFIMAN",
    "Susvara": "HIFIMAN",
    "Susvara Unveiled": "HIFIMAN",
    # JBL
    "JR 460NC": "JBL",
    "Junior 320": "JBL",
    "Junior 320BT": "JBL",
    "Junior 470NC": "JBL",
    "Live 460NC": "JBL",
    "Live 660NC": "JBL",
    "Live 670NC": "JBL",
    "Live 770NC": "JBL",
    "Tour One M2": "JBL",
    "Tour One M3": "JBL",
    "Tour 720BT": "JBL",
    "Tune 500": "JBL",
    "Tune 510BT": "JBL",
    "Tune 520BT": "JBL",
    "Tune 520C": "JBL",
    "Tune 660NC": "JBL",
    "Tune 670NC": "JBL",
    "Tune 760NC": "JBL",
    "Tune 770NC": "JBL",
    # Meze
    "Liric": "Meze",
    "Elite Tungsten": "Meze",
    "Empyrean 2": "Meze",
    "Poet": "Meze",
    "Strada": "Meze",
    "105 AER": "Meze",
    "105 Silva": "Meze",
    "109 Pro": "Meze",
    "99 Classics": "Meze",
    "99 Neo": "Meze",
    # Moondrop
    "Cosmo": "Moondrop",
    "Moondrop Joker": "Moondrop",
    "Moondrop Edge": "",
    "Moondrop Horizon": "",
    "Moondrop Para": "Moondrop",
    "Para2": "Moondrop",
    "Skyland": "Moondrop",
    "Moondrop Void": "",
    "Venus": "Moondrop",
    # Sennheiser
    "HD 200 Pro": "Sennheiser",
    "HD 25": "Sennheiser",
    "HD 25 Light": "Sennheiser",
    "HD 25 Plus": "Sennheiser",
    "HD 26": "Sennheiser",
    "HD 280 Pro": "Sennheiser",
    "HD 300 Pro": "Sennheiser",
    "HD 300 Protect": "Sennheiser",
    "HD 400 Pro": "Sennheiser",
    "HD 490 Pro": "Sennheiser",
    "HMD 26 S": "Sennheiser",
    "HMD 300": "Sennheiser",
    "HME 27": "Sennheiser",
    # Shokz
    "Openmove": "Shokz",
    "Openrun": "Shokz",
    "Openrun Pro 2": "Shokz",
    "Openswim": "Shokz",
    "Openswim Pro": "Shokz",
    # Sony
    "MDR-MV1": "Sony",
    "MDR-ZX110": "Sony",
    "MDR-ZX110AP": "Sony",
    "MDR-ZX110NC": "Sony",
    "MDR-ZX330AP": "Sony",
    "MDR-M1": "Sony",
    "MDR-Z1R": "Sony",
    "MDR-7506": "Sony",
    "WH-CH520": "Sony",
    "WH-CH720N": "Sony",
    "WH-RF400": "Sony",
    "WH-1000XM4": "Sony",
    "WH-1000XM5": "Sony",
    "WH-1000XM6": "Sony",
}

EARBUD_MODEL_TO_BRAND = {
    # Apple
    "Airpods Pro 3": "Apple",
    "Airpods 4": "Apple",
    # Audio-Technica
    "ATH-CKS30TW+": "Audio-Technica",
    "ATH-CKS50TW2": "Audio-Technica",
    "ATH-CK2000Ti": "Audio-Technica",
    "ATH-CLR100iS": "Audio-Technica",
    "ATH-CM2000Ti": "Audio-Technica",
    "ATH-E40": "Audio-Technica",
    "ATH-E50": "Audio-Technica",
    "ATH-E70": "Audio-Technica",
    "ATH-IEX1": "Audio-Technica",
    "ATH-TWX7": "Audio-Technica",
    "ATH-TWX9": "Audio-Technica",
    # Beats
    "Powerbeats Fit": "Beats",
    "Solo Buds": "Beats",
    "Studio Buds": "Beats",
    # Beyerdynamic
    "Amiron Zero": "Beyerdynamic",
    "Amiron 200": "Beyerdynamic",
    "Amiron 300": "Beyerdynamic",
    "DT 70 IE": "Beyerdynamic",
    "DT 71 IE": "Beyerdynamic",
    "DT 72 IE": "Beyerdynamic",
    "DT 73 IE": "Beyerdynamic",
    # Bose
    "QuietComfort Earbuds": "Bose",
    "QuietComfort Ultra Earbuds": "Bose",
    "Ultra Open": "Bose",
    # JBL
    "Endurance Peak 2": "JBL",
    "Endurance Peak 3": "JBL",
    "Endurance Peak 4": "JBL",
    "Endurance Race TWS": "JBL",
    "Endurance Race 2": "JBL",
    "Endurance Run 2": "JBL",
    "Live Flex 3": "JBL",
    "Live Free 2 TWS": "JBL",
    "Live Beam 3": "JBL",
    "Live Buds 3": "JBL",
    "Live Pro 2 TWS": "JBL",
    "Reflect Flow Pro": "JBL",
    "Soundgear Sense": "JBL",
    "Tour Pro 2": "JBL",
    "Tour Pro 3": "JBL",
    "Tune ANC TWS": "JBL",
    "Tune Beam 2": "JBL",
    "Tune Buds": "JBL",
    "Tune Buds 2": "JBL",
    "Tune Flex": "JBL",
    "Tune Flex 2": "JBL",
    "Tune 130NC": "JBL",
    "Vibe Beam 2": "JBL",
    "Vibe Buds": "JBL",
    "Vibe Buds 2": "JBL",
    "Vibe Flex": "JBL",
    "Vibe Flex 2": "JBL",
    "Vibe 300TWS": "JBL",
    # JLab
    "Epic Air": "JLab",
    "Epic Air Sport": "JLab",
    "Epic Lab": "JLab",
    "Epic Open Sport": "JLab",
    "Epic Pods": "JLab",
    "Epic Sport ANC 3": "JLab",
    "Go Air Tones": "JLab",
    "Go Pods": "JLab",
    "Go Pop": "JLab",
    "Go Pop+": "JLab",
    "Go Tones+": "JLab",
    "Jbuds Air": "JLab",
    "Jbuds Air Pro": "JLab",
    "Jbuds Air Sport": "JLab",
    "Jbuds ANC 3": "JLab",
    "Jbuds J6MS": "JLab",
    "Jbuds Mini": "JLab",
    "Jbuds Open Sport": "JLab",
    "Jbuds Pods": "JLab",
    "Jbuds Pro": "JLab",
    "Jbuds2": "JLab",
    # Moondrop
    "Alice": "Moondrop",
    "Aria2": "Moondrop",
    "Chu 2": "Moondrop",
    "DarkSaber": "Moondrop",
    "Dusk": "Moondrop",
    "Harmon": "Moondrop",
    "Golden Ages": "Moondrop",
    "Illustrious": "Moondrop",
    "Kadenz": "Moondrop",
    "Meteor": "Moondrop",
    "Moca": "Moondrop",
    "Moondrop Block": "",
    "Moondrop Concerto": "",
    "Moondrop May": "",
    "Moondrop Pill": "",
    "Moondrop Rays": "",
    "Moondrop Sparks": "",
    "Moondrop UltraSonic": "",
    "Nekocake": "Moondrop",
    "Psyche": "Moondrop",
    "Quark2": "Moondrop",
    "Solis 2": "Moondrop",
    "Space Travel": "Moondrop",
    "Space Travel 2": "Moondrop",
    "Space Travel 2 Ultra": "Moondrop",
    "Starfield 2": "Moondrop",
    "Voyager": "Moondrop",
    # Shokz
    "Opendots One": "Shokz",
    "Openfit Air": "Shokz",
    "Openfit Pro": "Shokz",
    "Openfit 2": "Shokz",
    # Sony
    "Inzone Buds": "Sony",
    "LinkBuds": "Sony",
    "LinkBuds Clip": "Sony",
    "LinkBuds Fit": "Sony",
    "WF-C510": "Sony",
    "WF-C710N": "Sony",
    "WF-1000XM5": "Sony",
    "WF-1000XM6": "Sony",
    # Soundcore
    "AeroClip": "Soundcore",
    "Aerofit Pro": "Soundcore",
    "Aerofit 2": "Soundcore",
    "Aerofit 2 Pro": "Soundcore",
    "C30i": "Soundcore",
    "C40i": "Soundcore",
    "C50i": "Soundcore",
    "Liberty 4": "Soundcore",
    "Liberty 4 Pro": "Soundcore",
    "Liberty 5": "Soundcore",
    "P20i": "Soundcore",
    "P30i": "Soundcore",
    "P31i": "Soundcore",
    "P40i": "Soundcore",
    "P41i": "Soundcore",
    "Sleep A20": "Soundcore",
    "Sleep A30": "Soundcore",
    "Space A40": "Soundcore",
    "Sport X10": "Soundcore",
    "Sport X20": "Soundcore",
    "V30i": "Soundcore",
    "V40i": "Soundcore",
}

DAC_MODEL_TO_BRAND = {""}
