HEADPHONE_MODEL_TO_BRAND = {
    # AKG
    "K72": "AKG",
    "K92": "AKG",
    "K182": "AKG",
    "K240 MK2": "AKG",
    "K240 Studio": "AKG",
    "K361": "AKG",
    "K361-BT": "AKG",
    "K371": "AKG",
    "K371-BT": "AKG",
    "Lyra": "AKG",
    "Y500 Wireless": "AKG",
    # Apple
    "Airpods Max": "Apple",
    # Audeze
    "CRBN2": "Audeze",
    "LCD-MX4": "Audeze",
    "LCD-S20": "Audeze",
    "LCD-X": "Audeze",
    "LCD-XS": "Audeze",
    "LCD-2": "Audeze",
    "LCD-2 Classic": "Audeze",
    "LCD-3": "Audeze",
    "LCD-4z": "Audeze",
    "LCD-5s": "Audeze",
    "MM-100": "Audeze",
    "MM-500": "Audeze",
    # Audio-Technica
    "ATH-ADX3000": "Audio-Technica",
    "ATH-ADX5000": "Audio-Technica",
    "ATH-ADX7000": "Audio-Technica",
    "ATH-AD500X": "Audio-Technica",
    "ATH-AD700X": "Audio-Technica",
    "ATH-AD900X": "Audio-Technica",
    "ATH-AWAS": "Audio-Technica",
    "ATH-AWKG": "Audio-Technica",
    "ATH-AWKT": "Audio-Technica",
    "ATH-AVC200": "Audio-Technica",
    "ATH-AVC400": "Audio-Technica",
    "ATH-A550Z": "Audio-Technica",
    "ATH-A990Z": "Audio-Technica",
    "ATH-M20X": "Audio-Technica",
    "ATH-M20XBT": "Audio-Technica",
    "ATH-M30X": "Audio-Technica",
    "ATH-M40X": "Audio-Technica",
    "ATH-M50X": "Audio-Technica",
    "ATH-M50XBT2": "Audio-Technica",
    "ATH-M60XA": "Audio-Technica",
    "ATH-M70X": "Audio-Technica",
    "ATH-R30X": "Audio-Technica",
    "ATH-R50X": "Audio-Technica",
    "ATH-R70XA": "Audio-Technica",
    "ATH-S120C": "Audio-Technica",
    "ATH-S220BT": "Audio-Technica",
    "ATH-S300BT": "Audio-Technica",
    "ATH-WBLTD": "Audio-Technica",
    "ATH-WP900": "Audio-Technica",
    # Beats
    "Solo 4": "Beats",
    "Studio Pro": "Beats",
    # Beyerdynamic
    "Amiron Home": "Beyerdynamic",
    "Amiron Wireless": "Beyerdynamic",
    "Aventho 100": "Beyerdynamic",
    "Aventho 300": "Beyerdynamic",
    "BT 900 Pro X": "Beyerdynamic",
    "DT 100": "Beyerdynamic",
    "DT 150": "Beyerdynamic",
    "DT 1770 Pro Mk1": "Beyerdynamic",
    "DT 1770 Pro MK2": "Beyerdynamic",
    "DT 1990 Pro MK2": "Beyerdynamic",
    "DT 250": "Beyerdynamic",
    "DT 252": "Beyerdynamic",
    "DT 270 Pro": "Beyerdynamic",
    "DT 700 Pro X": "Beyerdynamic",
    "DT 770 M": "Beyerdynamic",
    "DT 770 Pro": "Beyerdynamic",
    "DT 770 Pro X": "Beyerdynamic",
    "DT 880": "Beyerdynamic",
    "DT 880 Pro": "Beyerdynamic",
    "DT 990": "Beyerdynamic",
    "DT 990 Pro": "Beyerdynamic",
    "DT 990 Pro X": "Beyerdynamic",
    "DJ 300 Pro X": "Beyerdynamic",
    "TYGR 300 R": "Beyerdynamic",
    # Bose
    "QuietComfort": "Bose",
    "QuietComfort Ultra": "Bose",
    # Focal
    "Azurys": "Focal",
    "Bathys": "Focal",
    "Bathys MG": "Focal",
    "Clear MG": "Focal",
    "Hadenys": "Focal",
    "Lensys": "Focal",
    "Utopia": "Focal",
    "Stellia": "Focal",
    # HIFIMAN
    "Ananda Nano": "HIFIMAN",
    "Ananda Stealth Magnet": "HIFIMAN",
    "Arya": "HIFIMAN",
    "Arya Organic": "HIFIMAN",
    "Audivinia": "HIFIMAN",
    "Edition XS": "HIFIMAN",
    "Edition X V2": "HIFIMAN",
    "HE-R10D": "HIFIMAN",
    "HE-R10P": "HIFIMAN",
    "HE-500": "HIFIMAN",
    "HE1000se": "HIFIMAN",
    "HE1000 Stealth": "HIFIMAN",
    "HE1000 V2": "HIFIMAN",
    "HE400i": "HIFIMAN",
    "HE5se": "HIFIMAN",
    "HE560": "HIFIMAN",
    "HE6": "HIFIMAN",
    "HE6se": "HIFIMAN",
    "ISVARNA": "HIFIMAN",
    "Jade II Electrostatic": "HIFIMAN",
    "Shangri-La": "HIFIMAN",
    "Shangri-La JR": "HIFIMAN",
    "Sundara": "HIFIMAN",
    "Susvara": "HIFIMAN",
    "Susvara Unveiled": "HIFIMAN",
    # JBL
    "JR 460NC": "JBL",
    "Junior 320": "JBL",
    "Junior 320BT": "JBL",
    "Junior 470NC": "JBL",
    "Live 460NC": "JBL",
    "Live 660NC": "JBL",
    "Live 670NC": "JBL",
    "Live 770NC": "JBL",
    "Tour One M2": "JBL",
    "Tour One M3": "JBL",
    "Tour 720BT": "JBL",
    "Tune 500": "JBL",
    "Tune 510BT": "JBL",
    "Tune 520BT": "JBL",
    "Tune 520C": "JBL",
    "Tune 660NC": "JBL",
    "Tune 670NC": "JBL",
    "Tune 760NC": "JBL",
    "Tune 770NC": "JBL",
    # Meze
    "Liric": "Meze",
    "Elite Tungsten": "Meze",
    "Empyrean 2": "Meze",
    "Poet": "Meze",
    "Strada": "Meze",
    "105 AER": "Meze",
    "105 Silva": "Meze",
    "109 Pro": "Meze",
    "99 Classics": "Meze",
    "99 Neo": "Meze",
    # Moondrop
    "Cosmo": "Moondrop",
    "Moondrop Joker": "Moondrop",
    "Moondrop Edge": "",
    "Moondrop Horizon": "",
    "Moondrop Para": "Moondrop",
    "Para2": "Moondrop",
    "Skyland": "Moondrop",
    "Moondrop Void": "",
    "Venus": "Moondrop",
    # Sennheiser
    "HD 200 Pro": "Sennheiser",
    "HD 25": "Sennheiser",
    "HD 25 Light": "Sennheiser",
    "HD 25 Plus": "Sennheiser",
    "HD 26": "Sennheiser",
    "HD 280 Pro": "Sennheiser",
    "HD 300 Pro": "Sennheiser",
    "HD 300 Protect": "Sennheiser",
    "HD 400 Pro": "Sennheiser",
    "HD 490 Pro": "Sennheiser",
    "HMD 26 S": "Sennheiser",
    "HMD 300": "Sennheiser",
    "HME 27": "Sennheiser",
    # Shokz
    "Openmove": "Shokz",
    "Openrun": "Shokz",
    "Openrun Pro 2": "Shokz",
    "Openswim": "Shokz",
    "Openswim Pro": "Shokz",
    # Sony
    "MDR-MV1": "Sony",
    "MDR-ZX110": "Sony",
    "MDR-ZX110AP": "Sony",
    "MDR-ZX110NC": "Sony",
    "MDR-ZX330AP": "Sony",
    "MDR-M1": "Sony",
    "MDR-Z1R": "Sony",
    "MDR-7506": "Sony",
    "WH-CH520": "Sony",
    "WH-CH720N": "Sony",
    "WH-RF400": "Sony",
    "WH-1000XM4": "Sony",
    "WH-1000XM5": "Sony",
    "WH-1000XM6": "Sony",
}

EARBUD_MODEL_TO_BRAND = {
    # Apple
    "Airpods Pro 3": "Apple",
    "Airpods 4": "Apple",
    # Audio-Technica
    "ATH-CKS30TW+": "Audio-Technica",
    "ATH-CKS50TW2": "Audio-Technica",
    "ATH-CK2000Ti": "Audio-Technica",
    "ATH-CLR100iS": "Audio-Technica",
    "ATH-CM2000Ti": "Audio-Technica",
    "ATH-E40": "Audio-Technica",
    "ATH-E50": "Audio-Technica",
    "ATH-E70": "Audio-Technica",
    "ATH-IEX1": "Audio-Technica",
    "ATH-TWX7": "Audio-Technica",
    "ATH-TWX9": "Audio-Technica",
    # Beats
    "Powerbeats Fit": "Beats",
    "Solo Buds": "Beats",
    "Studio Buds": "Beats",
    # Beyerdynamic
    "Amiron Zero": "Beyerdynamic",
    "Amiron 200": "Beyerdynamic",
    "Amiron 300": "Beyerdynamic",
    "DT 70 IE": "Beyerdynamic",
    "DT 71 IE": "Beyerdynamic",
    "DT 72 IE": "Beyerdynamic",
    "DT 73 IE": "Beyerdynamic",
    # Bose
    "QuietComfort Earbuds": "Bose",
    "QuietComfort Ultra Earbuds": "Bose",
    "Ultra Open": "Bose",
    # JBL
    "Endurance Peak 2": "JBL",
    "Endurance Peak 3": "JBL",
    "Endurance Peak 4": "JBL",
    "Endurance Race TWS": "JBL",
    "Endurance Race 2": "JBL",
    "Endurance Run 2": "JBL",
    "Live Flex 3": "JBL",
    "Live Free 2 TWS": "JBL",
    "Live Beam 3": "JBL",
    "Live Buds 3": "JBL",
    "Live Pro 2 TWS": "JBL",
    "Reflect Flow Pro": "JBL",
    "Soundgear Sense": "JBL",
    "Tour Pro 2": "JBL",
    "Tour Pro 3": "JBL",
    "Tune ANC TWS": "JBL",
    "Tune Beam 2": "JBL",
    "Tune Buds": "JBL",
    "Tune Buds 2": "JBL",
    "Tune Flex": "JBL",
    "Tune Flex 2": "JBL",
    "Tune 130NC": "JBL",
    "Vibe Beam 2": "JBL",
    "Vibe Buds": "JBL",
    "Vibe Buds 2": "JBL",
    "Vibe Flex": "JBL",
    "Vibe Flex 2": "JBL",
    "Vibe 300TWS": "JBL",
    # JLab
    "Epic Air": "JLab",
    "Epic Air Sport": "JLab",
    "Epic Lab": "JLab",
    "Epic Open Sport": "JLab",
    "Epic Pods": "JLab",
    "Epic Sport ANC 3": "JLab",
    "Go Air Tones": "JLab",
    "Go Pods": "JLab",
    "Go Pop": "JLab",
    "Go Pop+": "JLab",
    "Go Tones+": "JLab",
    "Jbuds Air": "JLab",
    "Jbuds Air Pro": "JLab",
    "Jbuds Air Sport": "JLab",
    "Jbuds ANC 3": "JLab",
    "Jbuds J6MS": "JLab",
    "Jbuds Mini": "JLab",
    "Jbuds Open Sport": "JLab",
    "Jbuds Pods": "JLab",
    "Jbuds Pro": "JLab",
    "Jbuds2": "JLab",
    # Moondrop
    "Alice": "Moondrop",
    "Aria2": "Moondrop",
    "Chu 2": "Moondrop",
    "DarkSaber": "Moondrop",
    "Dusk": "Moondrop",
    "Harmon": "Moondrop",
    "Golden Ages": "Moondrop",
    "Illustrious": "Moondrop",
    "Kadenz": "Moondrop",
    "Meteor": "Moondrop",
    "Moca": "Moondrop",
    "Moondrop Block": "",
    "Moondrop Concertro": "",
    "Moondrop May": "",
    "Moondrop Pill": "",
    "Moondrop Rays": "",
    "Moondrop Sparks": "",
    "Moondrop UltraSonic": "",
    "Nekocake": "Moondrop",
    "Psyche": "Moondrop",
    "Quark2": "Moondrop",
    "Solis 2": "Moondrop",
    "Space Travel": "Moondrop",
    "Space Travel 2": "Moondrop",
    "Space Travel 2 Ultra": "Moondrop",
    "Starfield 2": "Moondrop",
    "Voyager": "Moondrop",
    # Shokz
    "Opendots One": "Shokz",
    "Openfit Air": "Shokz",
    "Openfit Pro": "Shokz",
    "Openfit 2": "Shokz",
    # Sony
    "Inzone Buds": "Sony",
    "LinkBuds": "Sony",
    "LinkBuds Clip": "Sony",
    "LinkBuds Fit": "Sony",
    "WF-C510": "Sony",
    "WF-C710N": "Sony",
    "WF-1000XM5": "Sony",
    "WF-1000XM6": "Sony",
    # Soundcore
    "AeroClip": "Soundcore",
    "Aerofit Pro": "Soundcore",
    "Aerofit 2": "Soundcore",
    "Aerofit 2 Pro": "Soundcore",
    "C30i": "Soundcore",
    "C40i": "Soundcore",
    "C50i": "Soundcore",
    "Liberty 4": "Soundcore",
    "Liberty 4 Pro": "Soundcore",
    "Liberty 5": "Soundcore",
    "P20i": "Soundcore",
    "P30i": "Soundcore",
    "P31i": "Soundcore",
    "P40i": "Soundcore",
    "P41i": "Soundcore",
    "Sleep A20": "Soundcore",
    "Sleep A30": "Soundcore",
    "Space A40": "Soundcore",
    "Sport X10": "Soundcore",
    "Sport X20": "Soundcore",
    "V30i": "Soundcore",
    "V40i": "Soundcore",
}

SOUNDBAR_MODEL_TO_BRAND = {
    # Bose
    "Bose Smart": "",
    "Bose TV Speaker": "",
    "Bose 550": "",
    "Smart Ultra": "Bose",
    # Denon
    "DHT-S218": "Denon",
    "DHT-S316": "Denon",
    "DHT-S517": "Denon",
    "Home Sound Bar 550": "Denon",
    # Devialet
    "Dione": "Devialet",
    # Insignia
    "2.0 Mini": "Insignia",
    "5.1.2": "Insignia",
    # Klipsch
    "Flexus Core 100": "Klipsch",
    "Flexus Core 200": "Klipsch",
    "Flexus Core 300": "Klipsch",
    # LG
    "H7": "LG",
    "SC9S": "LG",
    "SG10TY": "LG",
    "SKM1": "LG",
    "SK1": "LG",
    "SLM5Y": "LG",
    "SPD7R": "LG",
    "SPM7A": "LG",
    "SP2": "LG",
    "SP7R": "LG",
    "SQC1": "LG",
    "SQC4R": "LG",
    "SQC5": "LG",
    "S20A": "LG",
    "S40T": "LG",
    "S40TR": "LG",
    "S55TR": "LG",
    "S60T": "LG",
    "S60TR": "LG",
    "S70TR": "LG",
    "S70TY": "LG",
    "S80TR": "LG",
    "S80TY": "LG",
    "S90TR": "LG",
    "S90TY": "LG",
    "S95AR": "LG",
    "S95TR": "LG",
    # Polk
    "Magnifi Max AX": "Polk",
    "Magnifi Max AX SR": "Polk",
    "Magnifi Mini AX": "Polk",
    "Polk React": "",
    "Signa S2": "Polk",
    "Signa S2D": "Polk",
    "Signa S3": "Polk",
    "Signa S4": "Polk",
    "Signa S4D": "Polk",
    # Samsung
    "B400F": "Samsung HW-",
    "B550F": "Samsung HW-",
    "B630F": "Samsung HW-",
    "B750F": "Samsung HW-",
    "LST70T": "Samsung HW-",
    "QS700F": "Samsung HW-",
    "Q600F": "Samsung HW-",
    "Q700D": "Samsung HW-",
    "Q800F": "Samsung HW-",
    "Q900F": "Samsung HW-",
    "Q990F": "Samsung HW-",
    "S50B": "Samsung HW-",
    "S60D": "Samsung HW-",
    "S61D": "Samsung HW-",
    "S700D": "Samsung HW-",
    "S800D": "Samsung HW-",
    "S801D": "Samsung HW-",
    # Sennheiser
    "Ambeo Max": "Sennheiser",
    "Ambeo Mini": "Sennheiser",
    "Ambeo Plus": "Sennheiser",
    # Sonos
    "Arc Ultra": "Sonos",
    "Beam 2": "Sonos",
    "Sonos Ray": "Sonos",
    # Sony
    "Bravia Theater Bar 6": "Sony",
    "Bravia Theater Bar 8": "Sony",
    "Bravia Theater Bar 9": "Sony",
    "Bravia Theater Quad": "Sony",
    "HT-A3000": "Sony",
    "HT-A5000": "Sony",
    "HT-S100F": "Sony",
    "HT-S2000": "Sony",
    "HT-S40R": "Sony",
    "HT-S400": "Sony",
    # Vizio
    "Elevate SE": "Vizio",
    # Yamaha
    "SR-B20A": "Yamaha",
    "SR-B30A": "Yamaha",
    "SR-B40A": "Yamaha",
    "SR-C20A": "Yamaha",
    "SR-C30A": "Yamaha",
    "True X Bar 40A": "Yamaha",
    "True X Bar 50A": "Yamaha",
    "True X Bar 90A": "Yamaha",
    "True X Surround 90A": "Yamaha",
}

DAC_MODEL_TO_BRAND = {
    # AudioQuest
    "DragonFly Black": "AudioQuest",
    "DragonFly Cobalt": "AudioQuest",
    "DragonFly Red": "AudioQuest",
    # Chord Electronics
    "Dave": "Chord",
    "Hugo TT 2": "Chord",
    "Hugo 2": "Chord",
    "Mojo 2": "Chord",
    "Qutest": "Chord",
    # Denafrips
    "Ares": "Denafrips",
    "Enyo": "Denafrips",
    "Pontus": "Denafrips",
    "Terminator": "Denafrips",
    "Terminator Plus": "Denafrips",
    "Venus": "Denafrips",
    # Gustard
    "A26 Dual": "Gustard",
    "R26": "Gustard",
    "X18": "Gustard",
    "X26 iii": "Gustard",
    "X30": "Gustard",
    # Ferrum
    "Erco": "Ferrum",
    "Wandla": "Ferrum",
    "Wandla GoldenSound": "Ferrum",
    "Wandla HP": "Ferrum",
    # FiiO
    "BTR3K": "FiiO",
    "BTR5": "FiiO",
    "BTR7": "FiiO",
    "BTR11": "FiiO",
    "BTR13": "FiiO",
    "BTR15": "FiiO",
    "BTR17": "FiiO",
    "D03K": "FiiO",
    "E10K": "FiiO",
    "K5 Pro": "FiiO",
    "K9": "FiiO",
    "K9 AKM": "FiiO",
    "K11": "FiiO",
    "K11R2R": "FiiO",
    "K13 R2R": "FiiO",
    "K15": "FiiO",
    "K17": "FiiO",
    "K19": "FiiO",
    "Q3-MQA": "FiiO",
    "Q7": "FiiO",
    "Q11": "FiiO",
    "Q15": "FiiO",
    "Retro Nano": "FiiO",
    # Hidizs
    "DH80": "Hidizs",
    "DH80s": "Hidizs",
    "S3 Pro": "Hidizs",
    "S8": "Hidizs",
    "S8 Pro Robin": "Hidizs",
    "S9 Pro": "Hidizs",
    "S9 Pro Plus": "Hidizs",
    # Holo Audio
    "Cyan 2": "Holo Audio",
    "Holo Audio May": "",
    "Spring 3": "Holo Audio",
    # iFi
    "Go blu Air": "iFi",
    "Go Link": "iFi",
    "Go Link Max": "iFi",
    "Go Link 2": "iFi",
    "iDSD Diablo 2": "iFi",
    "iDSD Valkyrie": "iFi",
    "NEO iDSD 3": "iFi",
    "uno": "iFi",
    "xDSD Gryphon Black": "iFi",
    "Zen Blue 3": "iFi",
    "Zen DAC 3": "iFi",
    # JDS Labs
    "Atom DAC 2": "JDS Labs",
    "Element III": "JDS Labs",
    "Elemenet IV": "JDS Labs",
    # Qudelix
    "Qudelix 5K": "",
    "T71": "Qudelix",
    # Questyle
    "M12i": "Questyle",
    "M15C": "Questyle",
    "M15i": "Questyle",
    "M18i": "Questyle",
    "CMA Fifteen": "Questyle",
    "CMA 18 Master": "Questyle",
    # Mola Mola
    "Kula": "Mola Mola",
    "Tambaqui": "Mola Mola",
    # RME
    "ADI-2": "RME",
    "ADI-8": "RME",
    "ADI-8 DS MK III": "RME",
    "M-1610 Pro": "RME",
    "M-1620 Pro": "RME",
    "M-1620 Pro D": "RME",
    "M-16 AD": "RME",
    "M-16 DA": "RME",
    "M-32 AD": "RME",
    "M-32 AD Pro": "RME",
    "M-32 AD Pro II": "RME",
    "M-32 AD Pro II-D": "RME",
    "M-32 DA": "RME",
    "M-32 DA Pro": "RME",
    "M-32 DA Pro II": "RME",
    "M-32 DA Pro II-D": "RME",
    # Schiit
    "Bifrost": "Schiit",
    "Gungnir 2": "Schiit",
    "Mimir": "Schiit",
    "Modi 5": "Schiit",
    "Yggdrasil": "Schiit",
    # Smsl
    "C100": "SMSL",
    "C200": "SMSL",
    "DL100": "SMSL",
    "DL200": "SMSL",
    "DL300": "SMSL",
    "DL400": "SMSL",
    "DO100": "SMSL",
    "DO100 Pro": "SMSL",
    "DO200": "SMSL",
    "DO200 MKII": "SMSL",
    "DO200 Pro": "SMSL",
    "DO300": "SMSL",
    "DO300EX": "SMSL",
    "DO400": "SMSL",
    "DS100": "SMSL",
    "D-6": "SMSL",
    "D-6S": "SMSL",
    "D12": "SMSL",
    "D200": "SMSL",
    "D300": "SMSL",
    "D400 ES": "SMSL",
    "D400 EX": "SMSL",
    "D400 Pro": "SMSL",
    "M300 SE": "SMSL",
    "M500 MKIII": "SMSL",
    "PS200": "SMSL",
    "RAW-MDA1": "SMSL",
    "SMSL D1": "",
    "SU-X": "SMSL",
    "SU-1": "SMSL",
    "SU-10": "SMSL",
    "SU-6": "SMSL",
    "SU-9": "SMSL",
    "SU-9n": "SMSL",
    "SU-9 Pro": "SMSL",
    "SU-9 Ultra": "SMSL",
    "VMV D1se 2": "SMSL",
    "VMV D2R": "SMSL",
    "VMV D3": "SMSL",
    # Topping
    "Centaurus": "Topping",
    "DM7": "Topping",
    "DX1": "Topping",
    "DX3 Pro+": "Topping",
    "DX5": "Topping",
    "DX5 II": "Topping",
    "DX5 Lite": "Topping",
    "DX7 Pro+": "Topping",
    "DX9": "Topping",
    "DX9 Discrete": "Topping",
    "D10s": "Topping",
    "D10 Balanced": "Topping",
    "D50s": "Topping",
    "D50 III": "Topping",
    "D70 Pro Octo": "Topping",
    "D70 Pro Sabre": "Topping",
    "D90 III Discrete": "Topping",
    "D90 III Sabre": "Topping",
    "D90LE": "Topping",
    "D90SE": "Topping",
    "D900": "Topping",
    "EX5": "Topping",
    "E30 II": "Topping",
    "E30 II Lite": "Topping",
    "E50": "Topping",
    "E50 II": "Topping",
    "E70": "Topping",
    "E70 Velvet": "Topping",
    "U90": "Topping",
}

SPEAKER_MODEL_TO_BRAND = {
    # Amazon
    "Echo Dot": "Amazon",
    "Echo Dot Max": "Amazon",
    "Echo Pop": "Amazon",
    "Echo Show 5": "Amazon",
    "Echo Show 8": "Amazon",
    "Echo Show 11": "Amazon",
    "Echo Show 15": "Amazon",
    "Echo Spot": "Amazon",
    "Echo Studio": "Amazon",
    # Apple
    "HomePod": "Apple",
    "HomePod Mini": "Apple",
    # Bose
    "SoundLink Flex": "Bose",
    "SoundLink Home": "Bose",
    "SoundLink Max": "Bose",
    "SoundLink Micro": "Bose",
    "SoundLink Plus": "Bose",
    "S1 Pro+": "Bose",
    # Elac
    "ARB51": "Elac Navis",
    "ARF51": "Elac Navis",
    "BS243.4": "Elac Carina",
    "BS283.2": "Elac Solano 2.0",
    "BS302": "Elac Line 300",
    "BS305": "Elac Elegant",
    "BS312.2": "Elac Elegant",
    "CBS503.2": "Elac Concertro 2.0",
    "CCS501": "Elac Concertro",
    "CCS501.2": "Elac Concertro 2.0",
    "CC241.4": "Elac Carina",
    "CC281.2": "Elac Solano 2.0",
    "CFS507.2": "Elac Concertro 2.0",
    "Concertro": "Elac",
    "Concertro S 503": "Elac",
    "Concertro S 507": "Elac",
    "Concertro S 509": "Elac",
    "Concertro 2.0": "Elac",
    "DA42": "Elac Debut 2.0",
    "DA43": "Elac Debut 3.0",
    "DBR62": "Elac Debut Reference",
    "DB52": "Elac Debut 2.0",
    "DB53": "Elac Debut 3.0",
    "DB62": "Elac Debut 2.0",
    "DB63": "Elac Debut 3.0",
    "DCB41": "Elac ConneX",
    "DCB61": "Elac Debut ConneX",
    "DCR52": "Elac Debut Reference",
    "DC52": "Elac Debut 2.0",
    "DC53": "Elac Debut 3.0",
    "DC62": "Elac Debut 2.0",
    "DC63": "Elac Debut 3.0",
    "DFR52": "Elac Debut Reference",
    "DF52": "Elac Debut 2.0",
    "DF53": "Elac Debut 3.0",
    "DF62": "Elac Debut 2.0",
    "DF63": "Elac Debut 3.0",
    "DOW42": "Elac Debut 2.0",
    "FS247.4": "Elac Carina",
    "FS287.2": "Elac Solano 2.0",
    "NAVA100": "Elac",
    "OW-V41L": "Elac Muro",
    "OW-V41S": "Elac Muro",
    "UBR62": "Elac Uni-FI Reference",
    "UB52": "Elac Uni-Fi 2.0",
    "UCR52": "Elac Uni-Fi Reference",
    "UC52": "Elac Uni-Fi 2.0",
    "UFR52": "Elac Uni-Fi Reference",
    "UF52": "Elac Uni-Fi 2.0",
    "VBS403.2": "Elac Vela 2.0",
    "VBS404.2": "Elac Vela 2.0",
    "VCC401.2": "Elac Vela 2.0",
    "VFS407.2": "Elac Vela 2.0",
    "VFS408.2": "Elac Vela 2.0",
    "VFS409.2": "Elac Vela 2.0",
    "WS1425": "Elac",
    "WS1445": "Elac",
    "WS1465": "Elac",
    "WS1645": "Elac",
    "WS1665": "Elac",
    # Focal
    "Aria SR900": "Focal",
    "Aria Evo X Center": "Focal",
    "Aria Evo X 1": "Focal",
    "Aria Evo X 2": "Focal",
    "Aria Evo X 3": "Focal",
    "Aria Evo X 4": "Focal",
    "Diablo Utopia Evo": "Focal",
    "Diva Mezza Utopia": "Focal",
    "Diva Utopia": "Focal",
    "Granda Utopia EM Evo": "Focal",
    "Kanta Center": "Focal",
    "Kanta 1": "Focal",
    "Kanta 2": "Focal",
    "Kanta 3": "Focal",
    "Maestro Utopia Evo": "Focal",
    "Mu-so Hekla": "Focal",
    "Scala Utopia Evo": "Focal",
    "Sib Evo 2.0": "Focal",
    "Sib Evo 5.1.2": "Focal",
    "Sopra Center": "Focal",
    "Sopra Surround": "Focal",
    "Sopra 1": "Focal",
    "Sopra 2": "Focal",
    "Sopra 3": "Focal",
    "SW 1000 BE": "Focal",
    "Stella Utopia EM Evo": "Focal",
    "Theva Center": "Focal",
    "Theva Surround": "Focal",
    "Theva 1": "Focal",
    "Theva 2": "Focal",
    "Theva 3": "Focal",
    "Theva 3-D": "Focal",
    "Vestia Center": "Focal",
    "Vestia 1": "Focal",
    "Vestia 2": "Focal",
    "Vestia 3": "Focal",
    "Vestia 4": "Focal",
    "Viva Utopia Evo": "Focal",
    # Google
    "Nest Audio": "Google",
    "Nest Mini": "Google",
    # JBL
    "Arena 6IW": "JBL",
    "Authentics 200": "JBL",
    "Authentics 300": "JBL",
    "Authentics 500": "JBL",
    "Boombox 3": "JBL",
    "Boombox 4": "JBL",
    "Charge Essential 2": "JBL",
    "Charge 5": "JBL",
    "Charge 6": "JBL",
    "Clip 5": "JBL",
    "Concel C83": "JBL",
    "Flip Essential 2": "JBL",
    "Flip 5": "JBL",
    "Flip 6": "JBL",
    "Flip 7": "JBL",
    "Go 3": "JBL",
    "Go 4": "JBL",
    "HDI-3600": "JBL",
    "HDI-3800": "JBL",
    "HDI-4500": "JBL",
    "JBL Grip": "",
    "L10 Classic": "JBL",
    "L100 Classic MKII": "JBL",
    "L82 Classic MKII": "JBL",
    "PartyBox Club 120": "JBL",
    "PartyBox Encore 2": "JBL",
    "PartyBox On-The-Go": "JBL",
    "PartyBox Stage 320": "JBL",
    "PartyBox Ultimate": "JBL",
    "PartyBox 110": "JBL",
    "PartyBox 310": "JBL",
    "PartyBox 710": "JBL",
    "PartyBox 720": "JBL",
    "Stage A170": "JBL",
    "Stage A180": "JBL",
    "Stage A190": "JBL",
    "Stage XD-5": "JBL",
    "Stage XD-6": "JBL",
    "Stage 200P": "JBL",
    "Stage 220P": "JBL",
    "Stage 240B": "JBL",
    "Stage 240H": "JBL",
    "Stage 245C": "JBL",
    "Stage 250B": "JBL",
    "Stage 250WL": "JBL",
    "Stage 260C": "JBL",
    "Stage 260CDT": "JBL",
    "Stage 260CSA": "JBL",
    "Stage 260F": "JBL",
    "Stage 260W": "JBL",
    "Stage 280C": "JBL",
    "Stage 280CSA": "JBL",
    "Stage 280F": "JBL",
    "Stage 280W": "JBL",
    "Studio 6IW": "JBL",
    "Studio 610": "JBL",
    "Studio 66LCR": "JBL",
    "Studio 698": "JBL",
    "Studio 8IW": "JBL",
    "Studio 88ICR": "JBL",
    "Wind 3": "JBL",
    "Wind 3S": "JBL",
    "Xtreme 2": "JBL",
    "Xtreme 3": "JBL",
    "Xtreme 4": "JBL",
    # Klipsch
    "Klipsch Austin": "",
    "Klipsch Detroit": "",
    "Flexus Surr 100": "Klipsch",
    "Flexus Surr 200": "Klipsch",
    "Klipsch Nashville": "",
    "RC-64 III": "Klipsch",
    "RF-7 III": "Klipsch",
    "RP-404C II": "Klipsch",
    "RP-500C II": "Klipsch",
    "RP-500M II": "Klipsch",
    "RP-500SA II": "Klipsch",
    "RP-5000F II": "Klipsch",
    "RP-502S II": "Klipsch",
    "RP-504C II": "Klipsch",
    "RP-600M II": "Klipsch",
    "RP-6000F II": "Klipsch",
    "RP-8000F II": "Klipsch",
    "RP-8060FA II": "Klipsch",
    "R-30C": "Klipsch",
    "R-40M": "Klipsch",
    "R-40PM": "Klipsch",
    "R-40SA": "Klipsch",
    "R-50C": "Klipsch",
    "R-50M": "Klipsch",
    "R-50PM": "Klipsch",
    "R-600F": "Klipsch",
    "R-605FA": "Klipsch",
    "R-800F": "Klipsch",
    "The Fives II": "Klipsch",
    "The Nines": "Klipsch",
    "The Nines II": "Klipsch",
    "The One Plus": "Klipsch",
    "The Sevens": "Klipsch",
    "The Sevens II": "Klipsch",
    "The Three Plus": "Klipsch",
    # Logitech
    "G560": "Logitech",
    "S150": "Logitech",
    "Z150": "Logitech",
    "Z207": "Logitech",
    "Z313": "Logitech",
    "Z407": "Logitech",
    "Z533": "Logitech",
    "Z625": "Logitech",
    "Z906": "Logitech",
    # Marshall
    "Action III": "Marshall",
    "Bromley 750": "Marshall",
    "Emberton II": "Marshall",
    "Emberton III": "Marshall",
    "Heddon": "Marshall",
    "Heston Sub 200": "Marshall",
    "Heston 120": "Marshall",
    "Heston 60": "Marshall",
    "Kilburn II": "Marshall",
    "Kilburn III": "Marshall",
    "Middleton II": "Marshall",
    "Stanmore III": "Marshall",
    "Stockwell II": "Marshall",
    "Tufton": "Marshall",
    "Willen II": "Marshall",
    "Woburn III": "Marshall",
    # Polk Audio
    "Monitor XT10": "Polk",
    "Monitor XT12": "Polk",
    "Monitor XT15": "Polk",
    "Monitor XT20": "Polk",
    "Monitor XT30": "Polk",
    "Monitor XT35": "Polk",
    "Monitor XT60": "Polk",
    "Monitor XT70": "Polk",
    "Monitor XT90": "Polk",
    "Reserve R100": "Polk",
    "Reserve R200": "Polk",
    "Reserve R300": "Polk",
    "Reserve R350": "Polk",
    "Reserve R400": "Polk",
    "Reserve R500": "Polk",
    "Reserve R600": "Polk",
    "Reserve R700": "Polk",
    "Reserve R900": "Polk",
    "Signature Elite ES10": "Polk",
    "Signature Elite ES12": "Polk",
    "Signature Elite ES15": "Polk",
    "Signature Elite ES20": "Polk",
    "Signature Elite ES30": "Polk",
    "Signature Elite ES35": "Polk",
    "Signature Elite ES50": "Polk",
    "Signature Elite ES55": "Polk",
    "Signature Elite ES60": "Polk",
    "Signature Elite ES90": "Polk",
    "SR2": "Polk",
    "T15": "Polk",
    "T30": "Polk",
    "T50": "Polk",
    # Sonos
    "Era 100": "Sonos",
    "Era 300": "Sonos",
    "Move 2": "Sonos",
    "Roam 2": "Sonos",
    "Sonos Five": "",
    # Sony
    "SS-CSEM2": "Sony",
    "SS-CS3M2": "Sony",
    "SS-CS5M2": "Sony",
    "SS-CS8M2": "Sony",
    "Ult Field 1": "Sony",
    "Ult Field 3": "Sony",
    "Ult Field 5": "Sony",
    "Ult Field 7": "Sony",
    "Ult Tower 9": "Sony",
    "Ult Tower 9AC": "Sony",
    "Ult Tower 10": "Sony",
    "XB100": "Sony",
    "XG300": "Sony",
    "XP700": "Sony",
    "XV500 X-Series": "Sony",
    "XV800 X-Series": "Sony",
    # Soundcore
    "Boom Go 3i": "Soundcore",
    "Boom 2": "Soundcore",
    "Boom 2 Plus": "Soundcore",
    "Boom 3i": "Soundcore",
    "Motion Boom": "Soundcore",
    "Motion Boom Plus": "Soundcore",
    "Motion X600": "Soundcore",
    "Motion 300": "Soundcore",
    "Rave 3S": "Soundcore",
    "Select 4 Go": "Soundcore",
    "Soundcore 1": "",
    "Soundcore 2": "",
    "Soundcore 3": "",
    # Ulimate Ears
    "Boom 4": "Ulimate Ears",
    "EpicBoom": "Ulimate Ears",
    "EverBoom": "Ulimate Ears",
    "HyperBoom": "Ulimate Ears",
    "MegaBoom 4": "Ulimate Ears",
    "Miniroll": "Ulimate Ears",
    "WonderBoom 4": "Ulimate Ears",
    # Wharfedale
    "Aston": "Wharfedale",
    "Aura C": "Wharfedale",
    "Aura CS": "Wharfedale",
    "Aura 1": "Wharfedale",
    "Aura 2": "Wharfedale",
    "Aura 3": "Wharfedale",
    "Aura 4": "Wharfedale",
    "Denton": "Wharfedale",
    "Diamond 11.CC": "Wharfedale",
    "Diamond 11.CS": "Wharfedale",
    "Diamond 12": "Wharfedale",
    "Diamond 12.C": "Wharfedale",
    "Diamond 12.Ci": "Wharfedale",
    "Diamond 12.0": "Wharfedale",
    "Diamond 12.0i": "Wharfedale",
    "Diamond 12.1": "Wharfedale",
    "Diamond 12.1i": "Wharfedale",
    "Diamond 12.2": "Wharfedale",
    "Diamond 12.2i": "Wharfedale",
    "Diamond 12.3": "Wharfedale",
    "Diamond 12.3Di": "Wharfedale",
    "Diamond 12.3i": "Wharfedale",
    "Diamond 12.4": "Wharfedale",
    "Diamond 12.4i": "Wharfedale",
    "Diamond 240": "Wharfedale",
    "Dovedale": "Wharfedale",
    "D300C": "Wharfedale",
    "Elysian 1": "Wharfedale",
    "Elysian 2": "Wharfedale",
    "Elysian 3": "Wharfedale",
    "Elysian 4": "Wharfedale",
    "Evo4.C": "Wharfedale",
    "Evo4.CS": "Wharfedale",
    "Evo4.1": "Wharfedale",
    "Evo4.3": "Wharfedale",
    "Evo4.4": "Wharfedale",
    "Evo 5.C": "Wharfedale",
    "Evo 5.1": "Wharfedale",
    "Evo 5.2": "Wharfedale",
    "Evo 5.3": "Wharfedale",
    "Evo 5.4": "Wharfedale",
    "Linton": "Wharfedale",
    "Super Denton": "Wharfedale",
}
