GAMING_MOUSE_MODEL_TO_BRAND = {
    # Corsair
    "Darkstar": "Corsair",
    "Dark Core RGB Pro": "Corsair",
    "Dark Core RGB Pro SE": "Corsair",
    "Harpoon RGB Pro": "Corsair",
    "Harpoon RGB": "Corsair",
    "Ironclaw": "Corsair",
    "Ironclaw RGB": "Corsair",
    "Ironclaw Wireless SE": "Corsair",
    "Katar Elite": "Corsair",
    "Katar Pro": "Corsair",
    "Katar Pro XT": "Corsair",
    "M55": "Corsair",
    "M65 RGB Elite": "Corsair",
    "M75": "Corsair",
    "M75 Air": "Corsair",
    "Nightsabre": "Corsair",
    "Nightsword": "Corsair",
    "Sabre RGB Pro": "Corsair",
    "Sabre v2 Pro": "Corsair",  # technically full name is sabre v2 pro ultralight
    "Scimitar Elite": "Corsair",
    "Scimitar Elite Wireless SE": "Corsair",
    "Scimitar Pro RGB": "Corsair",
    "Scimitar RGB Elite": "Corsair",
    # Endgame Gear
    "XM2we": "Endgame Gear",
    "OP1": "Endgame Gear",
    "OP1we": "Endgame Gear",
    "OP1w 4k": "Endgame Gear",
    "OP1 8k": "Endgame Gear",
    "XM1": "Endgame Gear",
    "XM1r": "Endgame Gear",
    "XM2w 4k": "Endgame Gear",
    "XM2 8k": "Endgame Gear",
    # Finalmouse
    "Scream One": "Finalmouse",
    "Starlight-12": "Finalmouse",
    "Starlight Pro": "Finalmouse",
    "UltralightX Guardian": "Finalmouse",
    "UltralightX Phantom": "Finalmouse",
    "Ultralight Phantom": "Finalmouse",
    "Ultralight Pro": "Finalmouse",
    "Ultralight Sunset": "Finalmouse",
    "Ultralight 2": "Finalmouse",
    "ULX Competition": "Finalmouse",
    "ULX Frostlord": "Finalmouse",
    "ULX Prophecy": "Finalmouse",
    "ULX Pro Series": "Finalmouse",
    "ULX Sakura": "Finalmouse",
    # Glorious
    "Model D3": "Glorious",
    "Model D 2": "Glorious",
    "Model I 2": "Glorious",
    "Model O3": "Glorious",
    "Model O Eternal": "Glorious",
    "Model O 2": "Glorious",
    "Model O 2 Mini": "Glorious",
    "Model O 2 Pro": "Glorious",
    "Series 2 Pro": "Glorious",
    # HyperX
    "Pulsefire Fuse": "HyperX",
    "Pulsefire Haste": "HyperX",
    "Pulsefire Haste 2": "HyperX",
    "Pulsefire Haste 2 Core": "HyperX",
    "Pulsefire Haste 2 Mini": "HyperX",
    "Pulsefire Haste 2 Pro": "HyperX",
    "Pulsefire Haste 2 S": "HyperX",
    "Pulsefire Saga": "HyperX",
    "Pulsefire Sage Pro": "HyperX",
    "Pulsefire Surge": "HyperX",
    # Keychron
    "BM22": "Keychron",
    "BM24": "Keychron",
    "BM25": "Keychron",
    "Keychron M1": "",
    "Keychron M2": "",
    "Keychron M3": "",
    "Keychron M4": "",
    "Keychron M5": "",
    "Keychron M6": "",
    "Keychron M7": "",
    "Lemokey G1": "Keychron",
    "Lemokey G2": "Keychron",
    "M1 Ultra-Light": "Keychron",
    "M2 Mini": "Keychron",
    "M3 Mini": "Keychron",
    # Lamzu
    "Atlantis": "Lamzu",
    "Atlantis Mini": "Lamzu",
    "Atlantis OG V2 Pro": "Lamzu",
    "Inca": "Lamzu",
    "Maya": "Lamzu",
    "Maya X": "Lamzu",
    "Maya 4k": "Lamzu",
    "Paro": "Lamzu",
    "Paro Aurora": "Lamzu",
    "Thorn 4k": "Lamzu",
    # Logitech
    "G203": "Logitech",
    "G305": "Logitech",
    "G309 Lightspeed": "Logitech",
    "G403": "Logitech",
    "G502": "Logitech",
    "G502 X": "Logitech",
    "G502 X Lightspeed": "Logitech",
    "G502 X Plus": "Logitech",
    "G703": "Logitech",
    "G705": "Logitech",
    "G903": "Logitech",
    "Pro X Superlight": "Logitech",
    "Pro X Superlight 2": "Logitech",
    "Pro X Superlight 2C": "Logitech",
    "Pro X Superlight 2 Dex": "Logitech",
    "Pro X Superlight 2 SE": "Logitech",
    "Pro X2 Superstrike": "Logitech",
    "Pro 2 Lightspeed": "Logitech",
    # Ninjutso
    "Katana": "Ninjutso",
    "Katana Superlight": "Ninjutso",
    "Origin One X": "Ninjutso",
    "Sora V2": "Ninjutso",
    "Ten Air": "Ninjutso",
    # Pulsar
    "eS FS-1": "Pulsar",
    "JV-X": "Pulsar",
    "Pulsar x2": "",
    "Pulsar x2a": "",
    "Pulsar x2h": "",
    "Pulsar x3": "",
    "Susanto x": "Pulsar",
    "Xlite": "Pulsar",
    "Xlite Crazylight": "Pulsar",
    "Xlite v4": "Pulsar",
    "x2a v3": "Pulsar",
    "x2h Crazylight": "Pulsar",
    "x2n Crazylight": "Pulsar",
    "x2 CrazyLight": "Pulsar",
    "x2 v3": "Pulsar",
    "x3h v3": "Pulsar",
    "x3 Crazylight": "Pulsar",
    "x3 LHD": "Pulsar",
    "x3 LHD Crazylight": "Pulsar",
    # Razer
    "Basilisk Mobile": "Razer",
    "Basilisk V3": "Razer",
    "Basilisk V3 Pro": "Razer",
    "Basilisk V3 X Hyperspeed": "Razer",
    "Cobra": "Razer",
    "Cobra Hyperspeed": "Razer",
    "Cobra Pro": "Razer",
    "Deathadder Essential": "Razer",
    "Deathadder V2 X Hyperspeed": "Razer",
    "Deathadder V3": "Razer",
    "Deathadder V3 Hyperspeed": "Razer",
    "Deathadder V3 Pro": "Razer",
    "Deathadder V4 Pro": "Razer",
    "Naga V2 Lightspeed": "Razer",
    "Naga V2 Pro": "Razer",
    "Viper V3 Hyperspeed": "Razer",
    "Viper V3 Pro": "Razer",
    "Viper V3 Pro SE": "Razer",
    # Roccat
    "Burst II Air": "Roccat",
    "Burst II Pro": "Roccat",
    "Kone II": "Roccat",
    "Kone II Air": "Roccat",
    "Kone XP Air": "Roccat",
    "Pure Air": "Roccat",
    "Pure Sel": "Roccat",
    # ROG
    "Chakram": "Asus ROG",
    "Chakram X Origin": "Asus ROG",
    "Gladius III Core": "Asus ROG",
    "Harpe Ace": "Asus ROG",
    "Harpe Ace Extreme": "Asus ROG",
    "Harpe Mini Ace": "Asus ROG",
    "Harpe Mini Core": "Asus ROG",
    "Keris": "Asus ROG",
    "Keris II": "Asus ROG",
    "Keris II Ace": "Asus ROG",
    "Spatha X": "Asus ROG",
    "Strix Impact III": "Asus ROG",
    # SteelSeries
    "Aeros 3": "SteelSeries",
    "Aeros 5": "SteelSeries",
    "Aeros 9": "SteelSeries",
    "Rival 3": "SteelSeries",
    "Rival 5": "SteelSeries",
    # Vaxee
    "NP-01": "Vaxee Zygen",
    "NP-01s Ergo": "Vaxee Zygen",
    "NP-01s V2": "Vaxee Zygen",
    "Outset AX": "Vaxee",
    "Vaxee E1": "",
    "XE-S": "Vaxee",
    "XE v2": "Vaxee",
    # Zowie
    "EC1-DW": "Zowie",
    "EC2-DW": "Zowie",
    "EC3-DW": "Zowie",
    "FK2-DW": "Zowie",
    "S2-DW": "Zowie",
    "U2-DW": "Zowie",
    "ZA13-DW": "Zowie",
}

# Controller specific keywords
# Platform, Ex: Windows controller, etc
# Wired or Wireless
# Latency?
CONTROLLER_MODEL_TO_BRAND = {
    # GameSir
    "Cyclone 2": "GameSir",
    "G7 HE": "GameSir",
    "G7 Pro": "GameSir",
    "G7 SE": "GameSir",
    "G8 Plus": "GameSir",
    "Kaleid": "GameSir",
    "Kaleid Flux": "GameSir",
    "Nova HD": "GameSir",
    "Nova Lite": "GameSir",
    "Nova 2 Lite": "GameSir",
    "Super Nova": "GameSir",
    "Tarantula Pro": "GameSir",
    "Tegenaria Lite": "GameSir",
    "T7": "GameSir",
    "T7 Pro": "GameSir",
    "X2s": "GameSir",
    "X3 Pro": "GameSir",
    "X4 Aileron": "GameSir",
    "X5s": "GameSir",
    "X5 Lite": "GameSir",
    # Gulikit
    "Elves": "Gulikit",
    "Elves Pro": "Gulikit",
    "Elves 2": "Gulikit",
    "Elves 2 Pro": "Gulikit",
    "ES Pro": "Gulikit",
    "Guilikit ES": "",
    "Gulikit KingKong": "",
    "KingKong Pro": "Gulikit",
    "KingKong 2": "Gulikit",
    "KingKong 2 Pro": "Gulikit",
    "KK2T": "Gulikit",
    "KK3": "Gulikit",
    "KK3 Max": "Gulikit",
    "KK3 Pro": "Gulikit",
    "TT Max": "Gulikit",
    "TT Pro": "Gulikit",
    "Zen Pro": "Gulikit",
    # Flydigi
    "Apex 5": "Flydigi",
    "Dune Fox": "Flydigi",
    "Vader 4 Pro": "Flydigi",
    # Razer
    "Raiju V3 Pro": "Razer",
    "Wolverine V3 Pro": "Razer",
    "Wolverine V3 Tournament Edition": "Razer",
    # Scuf Gaming
    "Envision": "Scuf",
    "Envision Pro": "Scuf",
    "Instinct Pro": "Scuf",
    "Scuf Reflex": "Scuf",
    "Valor Pro": "Scuf",
    # Victrix
    "Gambit Prime": "Victrix",
    "Pro BFG": "Victrix",
    # 8BitDo
    "M30": "8BitDo",
    "SN30": "8BitDo",
    "SN30 Pro": "8BitDo",
    "Ultimate Mini": "8BitDo",
    "Ultimate 2": "8BitDo",
    "Ultimate 2C": "8BitDo",
    "Zero 2": "8BitDo",
    "8BitDo Lite SE": "",
    "8BitDo Lite 2": "",
    "8BitDo Pro 2": "",
    "8BitDo Pro 3": "",
    "8BitDo Ultimate": "",
    "8BitDo 64 Controller": "",
}

GAMING_LAPTOP_MODEL_TO_BRAND = {
    # Acer
    "Nitro V 15": "Acer",
    "Nitro V 16": "Acer",
    "Nitro V 16 AI": "Acer",
    "Nitro V 16S": "Acer",
    "Nitro V 16S AI": "Acer",
    "Nitro 14": "Acer",
    "Nitro 16S AI": "Acer",
    "Predator Helios Neo 16 AI": "Acer",
    "Predator Helios Neo 18 AI": "Acer",
    "Predator Helios 18 AI": "Acer",
    "Predator Triton 14": "Acer",
    "Predator Triton 14 AI": "Acer",
    # Asus
    "ROG Flow z13": "Asus",
    "Strix G16": "Asus ROG",
    "Strix G18": "Asus ROG",
    "Strix Scar 16": "Asus ROG",
    "Strix Scar 18": "Asus ROG",
    "TUF Gaming A14": "Asus",
    "TUF Gaming A15": "Asus",
    "TUF Gaming A16": "Asus",
    "TUF Gaming A18": "Asus",
    "TUF Gaming F15": "Asus",
    "TUF Gaming F16": "Asus",
    "TUF Gaming F17": "Asus",
    "Zephyrus G14": "Asus ROG",
    "Zephyrus G16": "Asus ROG",
    # Dell
    "Alienware 16 Area-51": "Dell",
    "Alienware 16 Aurora": "Dell",
    "Alienware 16X Aurora": "Dell",
    "Alienware 18 Area-51": "Dell",
    "Inspiron 14": "Dell",
    # Gigabyte
    "Aorus Elite 16": "Gigabyte",
    "Aorus Master 16": "Gigabyte",
    "Aorus Master 18": "Gigabyte",
    "Aorus 7": "Gigabyte",
    "Aorus 15": "Gigabyte",
    "Aorus 15G": "Gigabyte",
    "Aorus 15P": "Gigabyte",
    "Aorus 15X": "Gigabyte",
    "Aorus 16": "Gigabyte",
    "Aorus 16X": "Gigabyte",
    "Aorus 17": "Gigabyte",
    "Aorus 17G": "Gigabyte",
    "Aorus 17H": "Gigabyte",
    "Aorus 17X": "Gigabyte",
    "Gigabyte Gaming A16": "",
    "Gigabyte Gaming A16 Pro": "",
    "Gigabyte Gaming A18": "",
    "G6X": "Gigabyte",
    # HP
    "Omen Max": "HP",
    "Omen Transcend": "HP",
    "Omen 16": "HP",
    "Victus 15": "HP",
    # Lenovo
    "Legion Pro 5": "Lenovo",
    "Legion Pro 5i": "Lenovo",
    "Legion Pro 7": "Lenovo",
    "Legion Pro 7i": "Lenovo",
    "Legion 5": "Lenovo",
    "Legion 5a": "Lenovo",
    "Legion 5i": "Lenovo",
    "Legion 7a": "Lenovo",
    "Legion 7i": "Lenovo",
    "Legion 9i": "Lenovo",
    # MSI
    "Crosshair A16 HX": "MSI",
    "Crosshair A18 HX": "MSI",
    "Crosshair 16 HX": "MSI",
    "Crosshair 18 HX": "MSI",
    "Cyborg A15": "MSI",
    "Cyborg A17": "MSI",
    "Cyborg 15": "MSI",
    "Cyborg 17": "MSI",
    "Katana A15": "MSI",
    "Katana 15 HX": "MSI",
    "Raider A18 HX": "MSI",
    "Raider GE68 HX": "MSI",
    "Raider GE78 HX": "MSI",
    "Raider 18 HX": "MSI",
    "Stealth A16": "MSI",
    "Stealth A18": "MSI",
    "Stealth 14": "MSI",
    "Stealth 16": "MSI",
    "Stealth 18": "MSI",
    "Stealth 18 HX": "MSI",
    "Thin A15": "MSI",
    "Thin 15": "MSI",
    "Titan GT77 HX": "MSI",
    "Titan 18 HX": "MSI",
    "Vector A16 HX": "MSI",
    "Vector A18 HX": "MSI",
    "Vector 16 HX": "MSI",
    "Vector 18 HX": "MSI",
    # Razer
    "Blade 14": "Razer",
    "Blade 15": "Razer",
    "Blade 16": "Razer",
    "Blade 18": "Razer",
}