ESPRESSO_MACHINE_MODEL_TO_BRAND_MAPPINGS = {
    # Breville
    "Bambino": "Breville",
    "Bambino Plus": "Breville",
    "Barista Express": "Breville",
    "Barista Express Impress": "Breville",
    "Barista Pro": "Breville",
    "Barista Touch": "Breville",
    "Barista Touch Impress": "Breville",
    "Dual Boiler": "Breville",
    "Oracle Dual Boiler": "Breville",
    "Oracle Jet": "Breville",
    # DeLonghi
    "Dedica": "DeLonghi",
    "Dedica Duo": "DeLonghi",
    "Dedica Maestro": "DeLonghi",
    "Dedica Maestro Plus": "DeLonghi",
    "Dinamica Plus": "DeLonghi",
    "ECP3630": "DeLonghi",
    "Eletta Explore": "DeLonghi",
    "Granlattissima": "DeLonghi",
    "La Specialista Arte Evo": "DeLonghi",
    "La Specialista Maestro": "DeLonghi",
    "La Specialista Opera": "DeLonghi",
    "La Specialista Touch": "DeLonghi",
    "Magnifica Evo": "DeLonghi",
    "Magnifica Plus": "DeLonghi",
    "Magnifica Start": "DeLonghi",
    "Nespresso CitiZ": "DeLonghi",
    "Nespresso Essenza Mini": "DeLonghi",
    "Nespresso Inissia": "DeLonghi",
    "Nespresso Lattissima One": "DeLonghi",
    "Nespresso Vertuo": "DeLonghi",
    "Nespresso VertuoNext": "DeLonghi",
    "Nespresso VertuoPlus Deluxe": "DeLonghi",
    "Nespresso Vertuo Lattissima": "DeLonghi",
    "Nespresso Vertuo Pop": "DeLonghi",
    "Rivelia": "DeLonghi",
    "Rivelia Automatic": "DeLonghi",
    "Stilosa": "DeLonghi",
    # Flair Espresso
    "Flair Classic": "",
    "Flair Go": "",
    "Flair Pro 3": "",
    "Flair 58": "",
    "Neo Flex": "Flair",
    "58 Plus 2": "Flair",
    # Gaggia
    "Accademia": "Gaggia",
    "Anima": "Gaggia",
    "Anima Prestige": "Gaggia",
    "Besana": "Gaggia",
    "Brera": "Gaggia",
    "Cadorna Barista Plus": "Gaggia",
    "Cadorna Milk": "Gaggia",
    "Cadorna Prestige": "Gaggia",
    "Carezza Deluxe": "Gaggia",
    "Classic Pro E24": "Gaggia",
    "Espresso Evolution": "Gaggia",
    "Gaggia Classic GT": "",
    "Magenta Plus": "Gaggia",
    "Magenta Prestige": "Gaggia",
    "Velasca": "Gaggia",
    "Velasca Prestige": "Gaggia",
    # La Marzocco
    "Gs3": "La Marzocco",
    "Leva x1": "La Marzocco",
    "Linea Mini": "La Marzocco",
    "Linea Micra": "La Marzocco",
    "Strada x1": "La Marzocco",
    # Lelit
    "Anna": "Lelit",
    "Anita": "Lelit",
    "Bianca": "Lelit",
    "Elizabeth": "Lelit",
    "Kate": "Lelit",
    "MaraX": "Lelit",
    "Victoria": "Lelit",
    # Jura
    "Ena 4": "Jura",
    "Ena 8": "Jura",
    "Giga 10": "Jura",
    "Jura C3": "",
    "Jura C9": "",
    "Jura E4": "",
    "Jura E6": "",
    "Jura E8": "",
    "Jura J8": "",
    "Jura S8": "",
    "Jura Z10": "",
    "J8 Twin": "Jura",
    # Miele
    "CM 5310": "Miele",
    "CM 6160": "Miele",
    "CM 6360": "Miele",
    "CM 7750": "Miele",
    "CVA 7370": "Miele",
    "CVA 7440": "Miele",
    "CVA 7445": "Miele",
    "CVA 7775": "Miele",
    "CVA 7840": "Miele",
    "CVA 7845": "Miele",
    "CVA 7875": "Miele",
    # Philips
    "LatteGo 3300": "Philips",
    "LatteGo 5500": "Philips",
    # Rocket Espresso
    "Appartamento": "Rocket",
    "Appartamento Tca": "Rocket",
    "Bicocca": "Rocket",
    "Epica": "Rocket",
    "Giotto Cronometro R": "Rocket",
    "Giotto Cronometro V": "Rocket",
    "Giotto Fast": "Rocket",
    "Mozzafiato Cronometro R": "Rocket",
    "Mozzafiato Cronometro V": "Rocket",
    "Mozzafiato Fast": "Rocket",
    "Porta VIA": "Rocket",
    "R Cinquantotto": "Rocket",
    "R Nine One": "Rocket",
    # Rancilio
    "Baby 9": "Rancilio",
    "Classe 11": "Rancilio",
    "Classe 20": "Rancilio",
    "Classe 5": "Rancilio",
    "Classe 5 Eco": "Rancilio",
    "Classe 7": "Rancilio",
    "Classe 9": "Rancilio",
    "Silvia": "Rancilio",
    "Silvia Pro X": "Rancilio",
    # Terra Kaffe
    "Demi": "Terra Kaffe",
    "TK-02": "Terra Kaffe",
}

AIRFRYER_MODEL_TO_BRAND_MAPPINGS = {
    # Bella
    "Bella Pro": "",
    "Pro SmartCrisp": "Bella",
    "Pro Trizone": "Bella",
    "Trizone": "Bella",
    # Black & Decker
    "Black+Decker Purifry": "",
    "Crisp 'N Bake": "Black+Decker",
    # Breville
    "Joule Oven Air Fryer Pro": "Breville",
    "Smart Oven Air Fryer": "Breville",
    "Smart Oven Air Fryer Pro": "Breville",
    # Chefman
    "Chefman Compact": "",
    "Chefman Double-basket": "",
    "Chefman Multifunctional Digital": "",
    "Crispinator": "Chefman",
    "Turbofry": "Chefman",
    "Turbofry Dual Basket": "Chefman",
    "Turbofry Touch": "Chefman",
    "TurboX": "Chefman",
    # Cosori
    "Cosori Dual Basket": "",
    "Cosori Iconic": "",
    "Cosori Pro LE": "",
    "Dual Blaze": "Cosori",
    "TurboBlaze": "Cosori",
    # Cruisinart
    "ADZ-112": "Cruisinart",
    "AIR-160": "Cruisinart",
    "AIR-200": "Cruisinart",
    "AIR-200": "Cruisinart",
    "AIR-212": "Cruisinart",
    "AIR-220": "Cruisinart",
    "AIR-80": "Cruisinart",
    "TOA-110": "Cruisinart",
    "TOA-112": "Cruisinart",
    "TOA-26": "Cruisinart",
    "TOA-65": "Cruisinart",
    "TOA-70": "Cruisinart",
    "TOA-95": "Cruisinart",
    # Dash
    "Aircrisp Pro": "Dash",
    "Chef Series": "",
    "Dash Compact": "",
    "Dash Deluxe": "",
    "Tasti-Crisp": "Dash",
    "Tasti-Crisp Express": "Dash",
    # Dreo
    "Combi": "Dreo Chefmaker",
    # Emeril
    "Lagasse Dual-zone 360": "Emril",
    "Lagasse Everyday 360": "Emril",
    # Gourmia
    "GAF1190": "Gourmia",
    "GAF1220": "Gourmia",
    "GAF1290": "Gourmia",
    "GAF228": "Gourmia",
    "GAF249": "Gourmia",
    "GAF265": "Gourmia",
    "GAF318": "Gourmia",
    "GAF326": "Gourmia",
    "GAF328": "Gourmia",
    "GAF375": "Gourmia",
    "GAF414": "Gourmia",
    "GAF476": "Gourmia",
    "GAF486": "Gourmia",
    "GAF518": "Gourmia",
    "GAF536": "Gourmia",
    "GAF556": "Gourmia",
    "GAF566": "Gourmia",
    "GAF575": "Gourmia",
    "GAF612": "Gourmia",
    "GAF615": "Gourmia",
    "GAF616": "Gourmia",
    "GAF625": "Gourmia",
    "GAF652": "Gourmia",
    "GAF680": "Gourmia",
    "GAF685": "Gourmia",
    "GAF686": "Gourmia",
    "GAF698": "Gourmia",
    "GAF7020": "Gourmia",
    "GAF734": "Gourmia",
    "GAF735": "Gourmia",
    "GAF778": "Gourmia",
    "GAF784": "Gourmia",
    "GAF789": "Gourmia",
    "GAF798": "Gourmia",
    "GAF823": "Gourmia",
    "GAF836": "Gourmia",
    "GAF838": "Gourmia",
    "GAF846": "Gourmia",
    "GAF856": "Gourmia",
    "GAF858": "Gourmia",
    "GAF956": "Gourmia",
    "GAF966": "Gourmia",
    "GAF969": "Gourmia",
    "GTF1130": "Gourmia",
    "GTF1150": "Gourmia",
    "GTF2440": "Gourmia",
    "GTF2448": "Gourmia",
    "GTF2468": "Gourmia",
    "GTF2480": "Gourmia",
    "GTF3588": "Gourmia",
    "GTF7335": "Gourmia",
    "GTF7350": "Gourmia",
    "GTF7360": "Gourmia",
    "GTF7450": "Gourmia",
    "GTF7460": "Gourmia",
    "GTF7465": "Gourmia",
    "GTF7520": "Gourmia",
    "GTF7600": "Gourmia",
    "GTF7650": "Gourmia",
    "GTF7655": "Gourmia",
    "GTF7660": "Gourmia",
    "GTF7690": "Gourmia",
    "GTF7698": "Gourmia",
    "GTF7860": "Gourmia",
    "GTF7900": "Gourmia",
    # Instant
    "Vortex": "Instant",
    "Vortex Chef Series": "Instant",
    "Vortex Mini": "Instant",
    "Vortex Plus": "Instant",
    "Vortex Plus Dual": "Instant",
    "Vortex Slim": "Instant",
    "Vortex Slim Chef Series": "Instant",
    # Ninja
    "Crispi": "Ninja",
    "Crispi Pro": "Ninja",
    "Double Stack": "Ninja",
    "Double Stack XL": "Ninja",
    "Foodi": "Ninja",
    "Foodi Dualzone": "Ninja",
    # NuWave
    "Bravo XL Pro": "Nuwave",
    "Brio": "Nuwave",
    "Brio Plus": "Nuwave",
    "Nuwave Duet": "",
    # Philips
    "Airfryer 2000": "Philips",
    "Airfryer 3000": "Philips",
    "Airfryer 3000 Dual Basket": "Philips",
    "Airfryer 5000 Dual Basket": "Philips",
    # PowerXL
    "Luminex": "Power XL",
    "Vortex Pro": "Power XL",
    # Proscenic
    "T21": "Proscenic",
    "T22": "Proscenic",
    # Toshiba
    "Toshiba Digital Air Fryer": "",
    # Tristar
    "Power AirFryer": "Tristar",
}

BLENDER_MODEL_TO_BRAND_MAPPING = {
    # Beast
    "Beast Go": "",
    "Beast Mini 600": "",
    "Mega 1200": "Beast",
    "Mega 1200 Plus": "Beast",
    "Mini 600 Plus": "Beast",
    "Mighty 850": "Beast",
    "Mighty 850 Plus": "Beast",
    # Black & Decker
    "Powercrush": "Black+Decker",
    "Black+Decker Quiet": "",
    # BlendJet
    "Blendjet 2": "",
    # Blendtec
    "Blendtec Bar": "",
    "Blendtec Chef": "",
    "Classic 575": "Blendtec",
    "Connoisseur 825": "Blendtec",
    "Designer 650": "Blendtec",
    "Designer 650 S": "Blendtec",
    "Professional 800": "Blendtec",
    "Stealth Nitro X": "Blendtec",
    "Stealth X": "Blendtec",
    "Stealth 885": "Blendtec",
    "Stealth 895": "Blendtec",
    "Zakarian Pro": "Blendtec",
    # Breville
    "Breville Q": "",
    "Fresh & Furious": "Breville",
    "Super Q": "Breville",
    # Hamilton Beach
    "Blend Now": "Hamilton Beach",
    "Go Sport": "Hamilton Beach",
    "Multiblend": "Hamilton Beach",
    "Personal Creations": "Hamilton Beach",
    "Powerblend Duo": "Hamilton Beach",
    "Power Elite": "Hamilton Beach",
    "PowerMax": "Hamilton Beach",
    "Smoothie Smart": "Hamilton Beach",
    "Wave Action": "Hamilton Beach",
    "Wave Crusher": "Hamilton Beach",
    # KitchenAid
    "KitchenAid Go": "",
    "K150": "KitchenAid",
    "K400": "KitchenAid",
    "Pure Power": "KitchenAid",
    # Ninja
    "Blast Max": "Ninja",
    "BlendBoss": "Ninja",
    "Foodi Power Blender": "Ninja",
    "Ninja Blast": "",
    "Ninja Detect": "",
    "Ninja Detect Duo": "",
    "Ninja Professional Plus": "",
    "Nutri-Blender Pro": "Ninja",
    "Power Duo": "Ninja",
    "Twisti": "Ninja",
    "UltraCrush": "Ninja",
    # Oster
    "Oster One-Touch Blender": "",
    "Oster Party Blender": "",
    "Oster Pro Blender": "",
    "Oster Turbo Blender": "",
    # Vitamix
    "Ascent X2": "Vitamix",
    "Ascent X4": "Vitamix",
    "Ascent X5": "Vitamix",
    "A2500": "Vitamix",
    "A3500": "Vitamix",
    "Immersion": "Vitamix",
    "Propel 510": "Vitamix",
    "Propel 750": "Vitamix",
    "VX1": "Vitamix",
    "5200": "Vitamix",
}
