ESPRESSO_MACHINE_MODEL_TO_BRAND_MAPPINGS = {
    # Breville
    "Bambino": "Breville",
    "Bambino Plus": "Breville",
    "Barista Express": "Breville",
    "Barista Express Impress": "Breville",
    "Barista Pro": "Breville",
    "Barista Touch": "Breville",
    "Barista Touch Impress": "Breville",
    "Dual Boiler": "Breville",
    "Oracle Dual Boiler": "Breville",
    "Oracle Jet": "Breville",
    # DeLonghi
    "Dedica": "DeLonghi",
    "Dedica Duo": "DeLonghi",
    "Dedica Maestro": "DeLonghi",
    "Dedica Maestro Plus": "DeLonghi",
    "Dinamica Plus": "DeLonghi",
    "ECP3630": "DeLonghi",
    "Eletta Explore": "DeLonghi",
    "Granlattissima": "DeLonghi",
    "La Specialista Arte Evo": "DeLonghi",
    "La Specialista Maestro": "DeLonghi",
    "La Specialista Opera": "DeLonghi",
    "La Specialista Touch": "DeLonghi",
    "Magnifica Evo": "DeLonghi",
    "Magnifica Plus": "DeLonghi",
    "Magnifica Start": "DeLonghi",
    "Nespresso CitiZ": "DeLonghi",
    "Nespresso Essenza Mini": "DeLonghi",
    "Nespresso Inissia": "DeLonghi",
    "Nespresso Lattissima One": "DeLonghi",
    "Nespresso Vertuo": "DeLonghi",
    "Nespresso VertuoNext": "DeLonghi",
    "Nespresso VertuoPlus Deluxe": "DeLonghi",
    "Nespresso Vertuo Lattissima": "DeLonghi",
    "Nespresso Vertuo Pop": "DeLonghi",
    "Rivelia": "DeLonghi",
    "Rivelia Automatic": "DeLonghi",
    "Stilosa": "DeLonghi",
    # Flair Espresso
    "Flair Classic": "",
    "Flair Go": "",
    "Flair Pro 3": "",
    "Flair 58": "",
    "Neo Flex": "Flair",
    "58 Plus 2": "Flair",
    # Gaggia
    "Accademia": "Gaggia",
    "Anima": "Gaggia",
    "Anima Prestige": "Gaggia",
    "Besana": "Gaggia",
    "Brera": "Gaggia",
    "Cadorna Barista Plus": "Gaggia",
    "Cadorna Milk": "Gaggia",
    "Cadorna Prestige": "Gaggia",
    "Carezza Deluxe": "Gaggia",
    "Classic Pro E24": "Gaggia",
    "Espresso Evolution": "Gaggia",
    "Gaggia Classic GT": "",
    "Magenta Plus": "Gaggia",
    "Magenta Prestige": "Gaggia",
    "Velasca": "Gaggia",
    "Velasca Prestige": "Gaggia",
    # La Marzocco
    "Gs3": "La Marzocco",
    "Leva x1": "La Marzocco",
    "Linea Mini": "La Marzocco",
    "Linea Micra": "La Marzocco",
    "Strada x1": "La Marzocco",
    # Lelit
    "Anna": "Lelit",
    "Anita": "Lelit",
    "Bianca": "Lelit",
    "Elizabeth": "Lelit",
    "Kate": "Lelit",
    "MaraX": "Lelit",
    "Victoria": "Lelit",
    # Jura
    "Ena 4": "Jura",
    "Ena 8": "Jura",
    "Giga 10": "Jura",
    "Jura C3": "",
    "Jura C9": "",
    "Jura E4": "",
    "Jura E6": "",
    "Jura E8": "",
    "Jura J8": "",
    "Jura S8": "",
    "Jura Z10": "",
    "J8 Twin": "Jura",
    # Miele
    "CM 5310": "Miele",
    "CM 6160": "Miele",
    "CM 6360": "Miele",
    "CM 7750": "Miele",
    "CVA 7370": "Miele",
    "CVA 7440": "Miele",
    "CVA 7445": "Miele",
    "CVA 7775": "Miele",
    "CVA 7840": "Miele",
    "CVA 7845": "Miele",
    "CVA 7875": "Miele",
    # Philips
    "LatteGo 3300": "Philips",
    "LatteGo 5500": "Philips",
    # Rocket Espresso
    "Appartamento": "Rocket",
    "Appartamento Tca": "Rocket",
    "Bicocca": "Rocket",
    "Epica": "Rocket",
    "Giotto Cronometro R": "Rocket",
    "Giotto Cronometro V": "Rocket",
    "Giotto Fast": "Rocket",
    "Mozzafiato Cronometro R": "Rocket",
    "Mozzafiato Cronometro V": "Rocket",
    "Mozzafiato Fast": "Rocket",
    "Porta VIA": "Rocket",
    "R Cinquantotto": "Rocket",
    "R Nine One": "Rocket",
    # Rancilio
    "Baby 9": "Rancilio",
    "Classe 11": "Rancilio",
    "Classe 20": "Rancilio",
    "Classe 5": "Rancilio",
    "Classe 5 Eco": "Rancilio",
    "Classe 7": "Rancilio",
    "Classe 9": "Rancilio",
    "Silvia": "Rancilio",
    "Silvia Pro X": "Rancilio",
    # Terra Kaffe
    "Demi": "Terra Kaffe",
    "TK-02": "Terra Kaffe",
}
