SMARTPHONE_MODEL_TO_BRAND = {
    # Apple
    "iPhone Air": "Apple",
    "iPhone 16": "Apple",
    "iPhone 16e": "Apple",
    "iPhone 17": "Apple",
    "iPhone 17 Pro": "Apple",
    "iPhone 17 Pro Max": "Apple",
    "iPhone 18 Pro": "Apple",
    "iPhone 18 Pro Max": "Apple",
    # Asus
    "ROG Phone 8": "ASUS",
    "ROG Phone 8 Pro": "ASUS",
    "ROG Phone 9": "ASUS",
    "ROG Phone 9 Pro": "ASUS",
    "Zenfone 11 Ultra": "ASUS",
    "Zenfone 12 Ultra": "ASUS",
    # Google
    "Pixel 8a": "Google",
    "Pixel 8 Pro": "Google",
    "Pixel 9": "Google",
    "Pixel 9a": "Google",
    "Pixel 9 Pro": "Google",
    "Pixel 9 Pro Fold": "Google",
    "Pixel 9 Pro XL": "Google",
    "Pixel 10": "Google",
    "Pixel 10a": "Google",
    "Pixel 10 Pro": "Google",
    "Pixel 10 Pro Fold": "Google",
    "Pixel 10 Pro XL": "Google",
    # Motorola
    "Edge 2024": "Motorola",
    "Edge 2025": "Motorola",
    "G Play 2024": "Motorola",
    "G Play 2025": "Motorola",
    "G Play 2026": "Motorola",
    "G Power 2024": "Motorola",
    "G Power 2025": "Motorola",
    "G Power 2026": "Motorola",
    "G Power 5g 2024": "Motorola",
    "G Stylus 5g 2024": "Motorola",
    "G 5G 2024": "Motorola",
    "Razr+ 2024": "Motorola",
    "Razr+ 2025": "Motorola",
    "Razr Ultra 2025": "Motorola",
    "Razr 2024": "Motorola",
    "Razr 2025": "Motorola",
    # Oneplus
    "Oneplus 13": "",
    "Oneplus 15": "",
    "15R": "Oneplus",
    # Oppo
    "A15": "Oppo",
    "A15s": "Oppo",
    "A16": "Oppo",
    "A16k": "Oppo",
    "A17": "Oppo",
    "A17k": "Oppo",
    "A18": "Oppo",
    "A3": "Oppo",
    "A3x": "Oppo",
    "A3 Pro": "Oppo",
    "A38": "Oppo",
    "A5": "Oppo",
    "A5i": "Oppo",
    "A5i Pro": "Oppo",
    "A5x": "Oppo",
    "A5 Pro": "Oppo",
    "A54": "Oppo",
    "A57": "Oppo",
    "A57s": "Oppo",
    "A58": "Oppo",
    "A6": "Oppo",
    "A6s": "Oppo",
    "A6t": "Oppo",
    "A6t Pro": "Oppo",
    "A6x": "Oppo",
    "A6 Pro": "Oppo",
    "A60": "Oppo",
    "A74": "Oppo",
    "A76": "Oppo",
    "A77": "Oppo",
    "A78": "Oppo",
    "A79": "Oppo",
    "A94": "Oppo",
    "A96": "Oppo",
    "A98": "Oppo",
    "Find N2 Flip": "Oppo",
    "Find N3": "Oppo",
    "Find N3 Flip": "Oppo",
    "Find N5": "Oppo",
    "Find X3 Pro": "Oppo",
    "Find X8": "Oppo",
    "Find X8 Pro": "Oppo",
    "Find X9": "Oppo",
    "Find X9 Pro": "Oppo",
    "Reno10": "Oppo",
    "Reno10 Pro": "Oppo",
    "Reno10 Pro+": "Oppo",
    "Reno11": "Oppo",
    "Reno11 F": "Oppo",
    "Reno11 Pro": "Oppo",
    "Reno12": "Oppo",
    "Reno12 F": "Oppo",
    "Reno12 Pro": "Oppo",
    "Reno13": "Oppo",
    "Reno13 F": "Oppo",
    "Reno13 Pro": "Oppo",
    "Reno14": "Oppo",
    "Reno14 F": "Oppo",
    "Reno14 Pro": "Oppo",
    "Reno15": "Oppo",
    "Reno15 F": "Oppo",
    "Reno15 Pro": "Oppo",
    "Reno15 Pro Max": "Oppo",
    "Reno5": "Oppo",
    "Reno5 Pro": "Oppo",
    "Reno6": "Oppo",
    "Reno6 Pro": "Oppo",
    "Reno7": "Oppo",
    "Reno7 Pro": "Oppo",
    "Reno7 Z": "Oppo",
    "Reno8 Pro": "Oppo",
    "Reno8 T": "Oppo",
    # Redmagic
    "Redmagic 10 Air": "",
    "Redmagic 10 Pro": "",
    "Redmagic 10s Pro": "",
    "Redmagic 11 Air": "",
    "Redmagic 11 Pro": "",
    "Redmagic 9 Pro": "",
    "Redmagic 9s Pro": "",
    # Samsung
    "Galaxy A16": "Samsung",
    "Galaxy A26": "Samsung",
    "Galaxy A36": "Samsung",
    "Galaxy A56": "Samsung",
    "Galaxy S23": "Samsung",
    "Galaxy S23+": "Samsung",
    "Galaxy S23 FE": "Samsung",
    "Galaxy S23 Ultra": "Samsung",
    "Galaxy S24": "Samsung",
    "Galaxy S24+": "Samsung",
    "Galaxy S24 FE": "Samsung",
    "Galaxy S25": "Samsung",
    "Galaxy S25+": "Samsung",
    "Galaxy S25 Edge": "Samsung",
    "Galaxy S25 FE": "Samsung",
    "Galaxy S25 Ultra": "Samsung",
    "Galaxy S26": "Samsung",
    "Galaxy S26+": "Samsung",
    "Galaxy S26 Ultra": "Samsung",
    "Galaxy Z Flip5": "Samsung",
    "Galaxy Z Flip6": "Samsung",
    "Galaxy Z Flip7": "Samsung",
    "Galaxy Z Fold5": "Samsung",
    "Galaxy Z Fold6": "Samsung",
    "Galaxy Z Fold7": "Samsung",
    "Galaxy Z Trifold": "Samsung",
    # Vivo
    "V23": "Vivo",
    "V23e": "Vivo",
    "V23 Pro": "Vivo",
    "V25": "Vivo",
    "V25e": "Vivo",
    "V25 Pro": "Vivo",
    "V27": "Vivo",
    "V27e": "Vivo",
    "V27 Pro": "Vivo",
    "V29": "Vivo",
    "V29e": "Vivo",
    "V29 Lite": "Vivo",
    "V30": "Vivo",
    "V30e": "Vivo",
    "V30 Pro": "Vivo",
    "V40": "Vivo",
    "V40 Pro": "Vivo",
    "V50": "Vivo",
    "V50 Lite": "Vivo",
    "V60": "Vivo",
    "V60 Lite": "Vivo",
    "V70": "Vivo",
    "X100": "Vivo",
    "X100 Pro": "Vivo",
    "X200": "Vivo",
    "X200 FE": "Vivo",
    "X200 Pro": "Vivo",
    "X300": "Vivo",
    "X300 Pro": "Vivo",
    "X90": "Vivo",
    "X90 Pro": "Vivo",
    "X Fold3": "Vivo",
    "X Fold5": "Vivo",
    "Y02": "Vivo",
    "Y02s": "Vivo",
    "Y02t": "Vivo",
    "Y03": "Vivo",
    "Y03t": "Vivo",
    "Y04": "Vivo",
    "Y1s": "Vivo",
    "Y100": "Vivo",
    "Y100a": "Vivo",
    "Y12s": "Vivo",
    "Y15s": "Vivo",
    "Y16": "Vivo",
    "Y17s": "Vivo",
    "Y18": "Vivo",
    "Y19s": "Vivo",
    "Y20": "Vivo",
    "Y200": "Vivo",
    "Y21": "Vivo",
    "Y21s": "Vivo",
    "Y21T": "Vivo",
    "Y22": "Vivo",
    "Y22s": "Vivo",
    "Y27": "Vivo",
    "Y27s": "Vivo",
    "Y28": "Vivo",
    "Y28s": "Vivo",
    "Y29": "Vivo",
    "Y29s": "Vivo",
    "Y3s": "Vivo",
    "Y30": "Vivo",
    "Y31": "Vivo",
    "Y33s": "Vivo",
    "Y35": "Vivo",
    "Y36": "Vivo",
    "Y38": "Vivo",
    "Y39": "Vivo",
    "Y51": "Vivo",
    "Y53s": "Vivo",
    "Y55": "Vivo",
    "Y56": "Vivo",
    "Y72": "Vivo",
    "Y75": "Vivo",
    "Y76": "Vivo",
    "Y77": "Vivo",
    "Y78": "Vivo",
    # Xiaomi
    "Mix Flip": "Xiaomi",
    "Mix Fold 3": "Xiaomi",
    "Poco C61": "Xiaomi",
    "Poco C65": "Xiaomi",
    "Poco C71": "Xiaomi",
    "Poco C75": "Xiaomi",
    "Poco C85": "Xiaomi",
    "Poco F6": "Xiaomi",
    "Poco F6 Pro": "Xiaomi",
    "Poco F7": "Xiaomi",
    "Poco F7 Ultra": "Xiaomi",
    "Poco F8 Pro": "Xiaomi",
    "Poco F8 Ultra": "Xiaomi",
    "Poco M6": "Xiaomi",
    "Poco M6 Pro": "Xiaomi",
    "Poco M7": "Xiaomi",
    "Poco M7 Pro": "Xiaomi",
    "Poco M8": "Xiaomi",
    "Poco M8 Pro": "Xiaomi",
    "Poco X6": "Xiaomi",
    "Poco X6 Pro": "Xiaomi",
    "Poco X7": "Xiaomi",
    "Poco X7 Pro": "Xiaomi",
    "Redmi Note 13": "Xiaomi",
    "Redmi Note 13 Pro": "Xiaomi",
    "Redmi Note 13 Pro+": "Xiaomi",
    "Redmi Note 14": "Xiaomi",
    "Redmi Note 14s": "Xiaomi",
    "Redmi Note 14 Pro": "Xiaomi",
    "Redmi Note 14 Pro+": "Xiaomi",
    "Redmi Note 15": "Xiaomi",
    "Redmi Note 15 Pro": "Xiaomi",
    "Redmi Note 15 Pro+": "Xiaomi",
    "Redmi A3": "Xiaomi",
    "Redmi A3x": "Xiaomi",
    "Redmi A5": "Xiaomi",
    "Redmi 13": "Xiaomi",
    "Redmi 13c": "Xiaomi",
    "Redmi 13x": "Xiaomi",
    "Redmi 14C": "Xiaomi",
    "Redmi 15": "Xiaomi",
    "Redmi 15C": "Xiaomi",
    "Xiaomi 14": "",
    "Xiaomi 14t": "",
    "Xiaomi 14t Pro": "",
    "Xiaomi 14 Ultra": "",
    "Xiaomi 15": "",
    "Xiaomi 15t": "",
    "Xiaomi 15t Pro": "",
    "Xiaomi 15 Ultra": "",
    "Xiaomi 17": "",
    "Xiaomi 17 Ultra": "",
}
