CAMERA_MODEL_TO_BRAND = {
    # Canon
    "EOS Rebel T7": "Canon",
    "EOS RP": "Canon",
    "EOS R1": "Canon",
    "EOS R10": "Canon",
    "EOS R100": "Canon",
    "EOS R3": "Canon",
    "EOS R5": "Canon",
    "EOS R50": "Canon",
    "EOS R50 V": "Canon",
    "EOS R5 C": "Canon",
    "EOS R5 Mark II": "Canon",
    "EOS R6 Mark II": "Canon",
    "EOS R6 Mark III": "Canon",
    "EOS R7": "Canon",
    "EOS R8": "Canon",
    "EOS 5D Mark IV": "Canon",
    "PowerShot ELPH 360 HS": "Canon",
    "PowerShot G5 X Mark II": "Canon",
    "PowerShot G7 X Mark III": "Canon",
    "PowerShot SX740 HS": "Canon",
    "PowerShot V1": "Canon",
    # DJI
    "Osmo Action 4": "DJI",
    "Osmo Action 5 Pro": "DJI",
    "Osmo Action 6": "DJI",
    "Osmo Nano": "DJI",
    "Osmo 360": "DJI",
    "pocket 2": "DJI",
    "Pocket 3": "DJI",
    # Fujifilm
    "GFX100RF": "Fujifilm",
    "GFX100S II": "Fujifilm",
    "GFX100": "Fujifilm",
    "GFX100 II": "Fujifilm",
    "GFX-50R": "Fujifilm",
    "GFX50S II": "Fujifilm",
    "GFX Eterna 55": "Fujifilm",
    "GFX 50S": "Fujifilm",
    "X-E4": "Fujifilm",
    "X-E5": "Fujifilm",
    "X-H2": "Fujifilm",
    "X-H2S": "Fujifilm",
    "X-M5": "Fujifilm",
    "X-Pro3": "Fujifilm",
    "X-S10": "Fujifilm",
    "X-S20": "Fujifilm",
    "X-T200": "Fujifilm",
    "X-T3": "Fujifilm",
    "X-T3-WW": "Fujifilm",
    "X-T30": "Fujifilm",
    "X-T30 II": "Fujifilm",
    "X-T30 III": "Fujifilm",
    "X-T4": "Fujifilm",
    "X-T5": "Fujifilm",
    "X-T50": "Fujifilm",
    "X100V": "Fujifilm",
    "X100VI": "Fujifilm",
    # GoPro
    "GoPro Hero": "GoPro",
    "GoPro Max": "GoPro",
    "Hero 12": "GoPro",
    "Hero 13": "GoPro",
    "Hero 13 Black Ultra Wide": "GoPro",
    "Lit Hero": "GoPro",
    "Max 2": "GoPro",
    # Hasselblad
    "X1D II 50C": "Hasselblad",
    "X2D II 100C": "Hasselblad",
    "X2D 100C": "Hasselblad",
    # Insta360
    "Ace Pro": "Insta360",
    "Ace Pro 2": "Insta360",
    "One X2": "Insta360",
    "X3": "Insta360",
    "X4 Air": "Insta360",
    "X5": "Insta360",
    # Kodak
    "Ektar H35": "Kodak",
    "Ektar H35N": "Kodak",
    "Kodak i60": "",
    "Kodak M35": "",
    "Kodak M38": "",
    "Kodak S-88": "",
    "Mini Shot 2": "Kodak",
    "Mini Shot 3": "Kodak",
    "Mini Shot 4": "Kodak",
    "Pixpro AZ255": "Kodak",
    "Pixpro AZ405": "Kodak",
    "Pixpro AZ425": "Kodak",
    "Pixpro AZ528": "Kodak",
    "Pixpro AZ652": "Kodak",
    "Pixpro AZ901": "Kodak",
    "Pixpro C1": "Kodak",
    "Pixpro FZ45": "Kodak",
    "Pixpro FZ55": "Kodak",
    "Pixpro WPZ2": "Kodak",
    "Ultra F9": "Kodak",
    # Leica
    "D-Lux 8": "Leica",
    "Leica MP": "",
    "Leica M6": "",
    "Leica Q2": "",
    "Leica Q3": "",
    "M11": "Leica",
    "M11-D": "Leica",
    "M11-P": "Leica",
    "M EV1": "Leica",
    "Q2 Reporter": "Leica",
    "Q3 43": "Leica",
    "SL3": "Leica",
    "SL3-S": "Leica",
    "SL3 Reporter": "Leica",
    # Nikon
    "Coolpix P1100": "Nikon",
    "Coolpix P950": "Nikon",
    "D6": "Nikon",
    "D7500": "Nikon",
    "D780": "Nikon",
    "D850": "Nikon",
    "Nikon ZF": "",
    "Nikon ZR": "",
    "Zfc": "Nikon",
    "Z30": "Nikon",
    "Z5II": "Nikon",
    "Z50II": "Nikon",
    "Z6III": "Nikon",
    "Z7II": "Nikon",
    "Z8": "Nikon",
    "Z9": "Nikon",
    # OM System
    "OM-1": "OM System",
    "OM-1 Mark II": "OM System",
    "OM-3": "OM System",
    "OM-3 Astro": "OM System",
    "OM-5 Mark II": "OM System",
    "TG-7": "OM System",
    # Panasonic
    "FZ2500": "Panasonic Lumix",
    "FZ80": "Panasonic Lumix",
    "FZ80D": "Panasonic Lumix",
    "GH4": "Panasonic Lumix",
    "GH5": "Panasonic Lumix",
    "GH5M2": "Panasonic Lumix",
    "GH5S": "Panasonic Lumix",
    "GH6": "Panasonic Lumix",
    "GH7": "Panasonic Lumix",
    "GX85": "Panasonic Lumix",
    "GX9": "Panasonic Lumix",
    "G100D": "Panasonic Lumix",
    "G9II": "Panasonic Lumix",
    "Lumix G7": "Panasonic",
    "Lumix G85": "Panasonic",
    "Lumix G9": "Panasonic",
    "Lumix G95": "Panasonic",
    "Lumix G97": "Panasonic",
    "Lumix S1": "Panasonic",
    "Lumix S1H": "Panasonic",
    "Lumix S5": "Panasonic",
    "Lumix S9": "Panasonic",
    "S1II": "Panasonic Lumix",
    "S1IIE": "Panasonic Lumix",
    "S1R": "Panasonic Lumix",
    "S1RII": "Panasonic Lumix",
    "S5II": "Panasonic Lumix",
    "S5IIX": "Panasonic Lumix",
    "ZS99": "Panasonic Lumix",
    # Sony
    "Alpha ZV-E1": "Sony",
    "Alpha ZV-E10": "Sony",
    "Alpha ZV-E10 II": "Sony",
    "Alpha 1": "Sony",
    "Alpha 1 II": "Sony",
    "Alpha 6100": "Sony",
    "Alpha 6400": "Sony",
    "Alpha 6700": "Sony",
    "Alpha 7CR": "Sony",
    "Alpha 7C II": "Sony",
    "Alpha 7R IV": "Sony",
    "Alpha 7R V": "Sony",
    "Alpha 7S III": "Sony",
    "Alpha 7 III": "Sony",
    "Alpha 7 IV": "Sony",
    "Alpha 7 V": "Sony",
    "Alpha 9 III": "Sony",
}

TRIPOD_MODEL_TO_BRAND = {
    # Benro
    "Adventure 8X AL": "Benro",
    "Adventure 8X CF": "Benro",
    "Benro Adventure": "",
    "Benro Bat": "",
    "CyanBird": "Benro",
    "Cyanbird AL": "Benro",
    "Cyanbird CF": "Benro",
    "Kingpod CF": "Benro",
    "KoalaPod": "Benro",
    "Mach3 AL": "Benro",
    "Mach3 9X CF": "Benro",
    "Mammoth TMTH33C": "Benro",
    "Mammoth TMTH34C": "Benro",
    "Mammoth TMTH43C": "Benro",
    "Mammoth TMTH44C": "Benro",
    "MiniBird": "Benro",
    "PP1 PocketPod": "Benro",
    "Rhino": "Benro",
    "Superslim AL": "Benro",
    "Superslim CF": "Benro",
    "SystemGO Plus": "Benro",
    "Tablebird": "Benro",
    "Tortoise CF": "Benro",
    "Tripster": "Benro",
    # Gitzo
    "Mini Traveler": "Gitzo",
    "Mountaineer Series 0": "Gitzo",
    "Mountaineer Series 1": "Gitzo",
    "Mountaineer Series 2": "Gitzo",
    "Mountaineer Series 3": "Gitzo",
    "Systematic Series 3": "Gitzo",
    "Systematic Series 4": "Gitzo",
    "Systematic Series 5": "Gitzo",
    "Traveler Series 0": "Gitzo",
    "Traveler Series 1": "Gitzo",
    "Traveler Series 2": "Gitzo",
    # Joby
    "GorillaPod Go": "Joby",
    "GorillaPod 1K": "Joby",
    "GorillaPod 3K": "Joby",
    "HandyPod Clip": "Joby",
    # Manfrotto
    "Befree": "Manfrotto",
    "Befree Advanced": "Manfrotto",
    "Befree GT": "Manfrotto",
    "Befree Live": "Manfrotto",
    "Compact Action": "Manfrotto",
    "Compact Advanced": "Manfrotto",
    "Compact Light": "Manfrotto",
    "Manfrotto One": "",
    # RRS
    "Ascend-14": "RRS",
    "Ascend-14L": "RRS",
    "Ascend-14-bh": "RRS",
    "TFA-01": "RRS",
    "TFCT-14L": "RRS",
    "TFCT-24L": "RRS",
    "TFCT-33": "RRS",
    "TFCT-34": "RRS",
    "TFCT-34L": "RRS",
    "TFCX-13": "RRS",
    "TFCX-14L": "RRS",
    "Ultralight-24": "RRS",
    "Ultralight-24L": "RRS",
    "Ultralight-33": "RRS",
    "Ultralight-34": "RRS",
    "Ultralight-34L": "RRS",
    "Versa-22i": "RRS",
    "Versa-22iC": "RRS",
    "Versa-24": "RRS",
    "Versa-24L": "RRS",
    "Versa-32G": "RRS",
    "Versa-33": "RRS",
    "Versa-34": "RRS",
    "Versa-34L": "RRS",
    # Sirui
    "AM-223": "Sirui",
    "AM-225": "Sirui",
    "AM-284": "Sirui",
    "AM-324": "Sirui",
    "ET-1204": "Sirui",
    "ET-2004": "Sirui",
    "ET-2204": "Sirui",
    "ET1204": "Sirui",
    "SQ75": "Sirui",
    "SVS75": "Sirui",
    "SVT75": "Sirui",
    "Traveler 5A": "Sirui",
    "Traveler 5AX": "Sirui",
    "Traveler 5CX": "Sirui",
    "Traveler 7A": "Sirui",
    "Traveler 7C": "Sirui",
    "W-2204": "Sirui",
    # 3 Legged Thing
    "Albert 2.0": "3 Legged Thing",
    "Charles 2.0": "3 Legged Thing",
    "Legends Bucky": "3 Legged Thing",
    "Legends Jay": "3 Legged Thing",
    "Legends Mike": "3 Legged Thing",
    "Legends Ray": "3 Legged Thing",
    "Legends Tommy": "3 Legged Thing",
    "Leo 2.0": "3 Legged Thing",
    "Punks Billy 2.0": "3 Legged Thing",
    "Punks Brian 2.0": "3 Legged Thing",
    "Punks Corey 2.0": "3 Legged Thing",
    "Punks Patti 2.0": "3 Legged Thing",
    "Punks Travis 2.0": "3 Legged Thing",
    "Winston 2.0": "3 Legged Thing",
}

CAMERA_BACKPACK_MODEL_TO_BRAND = {
    # Gitzo
    "Adventury 30L": "Gitzo",
    "Adventury 45L": "Gitzo",
    "Lengende": "Gitzo",
}
