CAMERA_MODEL_TO_BRAND = {
    # Canon
    "EOS Rebel T7": "Canon",
    "EOS RP": "Canon",
    "EOS R1": "Canon",
    "EOS R10": "Canon",
    "EOS R100": "Canon",
    "EOS R3": "Canon",
    "EOS R5": "Canon",
    "EOS R50": "Canon",
    "EOS R50 V": "Canon",
    "EOS R5 C": "Canon",
    "EOS R5 Mark II": "Canon",
    "EOS R6 Mark II": "Canon",
    "EOS R6 Mark III": "Canon",
    "EOS R7": "Canon",
    "EOS R8": "Canon",
    "EOS 5D Mark IV": "Canon",
    "PowerShot ELPH 360 HS": "Canon",
    "PowerShot G5 X Mark II": "Canon",
    "PowerShot G7 X Mark III": "Canon",
    "PowerShot SX740 HS": "Canon",
    "PowerShot V1": "Canon",
    # DJI
    "Osmo Action 4": "DJI",
    "Osmo Action 5 Pro": "DJI",
    "Osmo Action 6": "DJI",
    "Osmo Nano": "DJI",
    "Osmo 360": "DJI",
    "pocket 2": "DJI",
    "Pocket 3": "DJI",
    # Fujifilm
    "GFX100RF": "Fujifilm",
    "GFX100S II": "Fujifilm",
    "GFX100": "Fujifilm",
    "GFX100 II": "Fujifilm",
    "GFX-50R": "Fujifilm",
    "GFX50S II": "Fujifilm",
    "GFX Eterna 55": "Fujifilm",
    "GFX 50S": "Fujifilm",
    "X-E4": "Fujifilm",
    "X-E5": "Fujifilm",
    "X-H2": "Fujifilm",
    "X-H2S": "Fujifilm",
    "X-M5": "Fujifilm",
    "X-Pro3": "Fujifilm",
    "X-S10": "Fujifilm",
    "X-S20": "Fujifilm",
    "X-T200": "Fujifilm",
    "X-T3": "Fujifilm",
    "X-T3-WW": "Fujifilm",
    "X-T30": "Fujifilm",
    "X-T30 II": "Fujifilm",
    "X-T30 III": "Fujifilm",
    "X-T4": "Fujifilm",
    "X-T5": "Fujifilm",
    "X-T50": "Fujifilm",
    "X100V": "Fujifilm",
    "X100VI": "Fujifilm",
    # GoPro
    "GoPro Hero": "GoPro",
    "GoPro Max": "GoPro",
    "Hero 12": "GoPro",
    "Hero 13": "GoPro",
    "Hero 13 Black Ultra Wide": "GoPro",
    "Lit Hero": "GoPro",
    "Max 2": "GoPro",
    # Hasselblad
    "X1D II 50C": "Hasselblad",
    "X2D II 100C": "Hasselblad",
    "X2D 100C": "Hasselblad",
    # Insta360
    "Ace Pro": "Insta360",
    "Ace Pro 2": "Insta360",
    "One X2": "Insta360",
    "X3": "Insta360",
    "X4 Air": "Insta360",
    "X5": "Insta360",
    # Kodak
    "Ektar H35": "Kodak",
    "Ektar H35N": "Kodak",
    "Kodak i60": "",
    "Kodak M35": "",
    "Kodak M38": "",
    "Kodak S-88": "",
    "Mini Shot 2": "Kodak",
    "Mini Shot 3": "Kodak",
    "Mini Shot 4": "Kodak",
    "Pixpro AZ255": "Kodak",
    "Pixpro AZ405": "Kodak",
    "Pixpro AZ425": "Kodak",
    "Pixpro AZ528": "Kodak",
    "Pixpro AZ652": "Kodak",
    "Pixpro AZ901": "Kodak",
    "Pixpro C1": "Kodak",
    "Pixpro FZ45": "Kodak",
    "Pixpro FZ55": "Kodak",
    "Pixpro WPZ2": "Kodak",
    "Ultra F9": "Kodak",
    # Leica
    "D-Lux 8": "Leica",
    "Leica MP": "",
    "Leica M6": "",
    "Leica Q2": "",
    "Leica Q3": "",
    "M11": "Leica",
    "M11-D": "Leica",
    "M11-P": "Leica",
    "M EV1": "Leica",
    "Q2 Reporter": "Leica",
    "Q3 43": "Leica",
    "SL3": "Leica",
    "SL3-S": "Leica",
    "SL3 Reporter": "Leica",
    # Nikon
    "Coolpix P1100": "Nikon",
    "Coolpix P950": "Nikon",
    "D6": "Nikon",
    "D7500": "Nikon",
    "D780": "Nikon",
    "D850": "Nikon",
    "Nikon ZF": "",
    "Nikon ZR": "",
    "Zfc": "Nikon",
    "Z30": "Nikon",
    "Z5II": "Nikon",
    "Z50II": "Nikon",
    "Z6III": "Nikon",
    "Z7II": "Nikon",
    "Z8": "Nikon",
    "Z9": "Nikon",
    # OM System
    "OM-1": "OM System",
    "OM-1 Mark II": "OM System",
    "OM-3": "OM System",
    "OM-3 Astro": "OM System",
    "OM-5 Mark II": "OM System",
    "TG-7": "OM System",
    # Panasonic
    "FZ2500": "Panasonic Lumix",
    "FZ80": "Panasonic Lumix",
    "FZ80D": "Panasonic Lumix",
    "GH4": "Panasonic Lumix",
    "GH5": "Panasonic Lumix",
    "GH5M2": "Panasonic Lumix",
    "GH5S": "Panasonic Lumix",
    "GH6": "Panasonic Lumix",
    "GH7": "Panasonic Lumix",
    "GX85": "Panasonic Lumix",
    "GX9": "Panasonic Lumix",
    "G100D": "Panasonic Lumix",
    "G9II": "Panasonic Lumix",
    "Lumix G7": "Panasonic",
    "Lumix G85": "Panasonic",
    "Lumix G9": "Panasonic",
    "Lumix G95": "Panasonic",
    "Lumix G97": "Panasonic",
    "Lumix S1": "Panasonic",
    "Lumix S1H": "Panasonic",
    "Lumix S5": "Panasonic",
    "Lumix S9": "Panasonic",
    "S1II": "Panasonic Lumix",
    "S1IIE": "Panasonic Lumix",
    "S1R": "Panasonic Lumix",
    "S1RII": "Panasonic Lumix",
    "S5II": "Panasonic Lumix",
    "S5IIX": "Panasonic Lumix",
    "ZS99": "Panasonic Lumix",
    # Sony
    "Alpha ZV-E1": "Sony",
    "Alpha ZV-E10": "Sony",
    "Alpha ZV-E10 II": "Sony",
    "Alpha 1": "Sony",
    "Alpha 1 II": "Sony",
    "Alpha 6100": "Sony",
    "Alpha 6400": "Sony",
    "Alpha 6700": "Sony",
    "Alpha 7CR": "Sony",
    "Alpha 7C II": "Sony",
    "Alpha 7R IV": "Sony",
    "Alpha 7R V": "Sony",
    "Alpha 7S III": "Sony",
    "Alpha 7 III": "Sony",
    "Alpha 7 IV": "Sony",
    "Alpha 7 V": "Sony",
    "Alpha 9 III": "Sony",
}
