- name: Include tunnel facts variables
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/cyphria_applications_roles/cloudflare-tunnel/credentials/temp.yaml"

- name: Deploy frontend
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'argo-cd-deployment.yaml') | from_yaml }}"
    kubeconfig: /etc/rancher/k3s/k3s.yaml
