- name: Role Provisioning
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: '{{ k3s_vars.server.api.port }}'
        timeout: 30
      any_errors_fatal: true

    - name: Deploy Prometheus Operator to ArgoCD
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'deploy_operator.yaml') | from_yaml }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml
    
    - name: Deploy Prometheus CRDS to ArgoCD
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'deploy_crds.yaml') | from_yaml }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml



