- name: Role Reset
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Remove Repo
      kubernetes.core.helm_repository:
        name: '{{ argocd_vars.kubernetes.helm.repository.org }}'
        repo_state: absent
    
    - name: Remove Calico CNI config files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/cni/net.d/10-calico.conflist
        - /etc/cni/net.d/calico-kubeconfig
      
    - name: remove binary
      ansible.builtin.file: 
        path: /usr/local/bin/argocd
        state: absent