- name: Role validation
  ansible.builtin.import_tasks:
    file: validation.yaml
  any_errors_fatal: true

- name: Calico Installation
  block: 
    - name: add repo
      kubernetes.core.helm_repository:
        name: "{{ calico_map.helm.repository.name }}"
        repo_url: "{{ calico_map.helm.repository.url }}"

    - name: Chart Setup 
      kubernetes.core.helm:
        name: "{{ calico_vars.kubernetes.helm.repository.org }}"
        chart_ref: "{{ calico_map.helm.chart.reference }}"
        kubeconfig: "{{ k3s_project.cluster.kubeconfig }}"
        chart_version: "{{ calico_vars.kubernetes.helm.chart.version }}"
        namespace: "{{ calico_vars.kubernetes.helm.namespace }}"
        create_namespace: true
        timeout: "{{ calico_map.helm.timeout }}"
        update_repo_cache: true
        wait: true
      register: result
      retries: 3
      delay: 1
      until: result is not failed
  
- name: Calicoctl Installation
  block:
    - name: Install binary
      ansible.builtin.get_url:
        url: "{{ calico_map.calicoctl.url }}"
        dest: "{{ k3s_map.node.directory.bin}}/calicoctl"
        owner: root
        group: root
        mode: '755'


    