apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: argocd-application-controller-network-policy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" 
spec:
  order: 80
  selector: "app.kubernetes.io/name == 'argocd-application-controller' ||
             app.kubernetes.io/name == 'argocd-metrics'"
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow # exposing ArgoCD application controller metrics endpoint
      protocol: TCP
      source: 
        namespaceSelector: kubernetes.io/metadata.name == "prometheus"
        selector: "app.kubernetes.io/instance == 'prometheus-operator' || 
                  app.kubernetes.io/instance == 'prometheus' || 
                  managed-by == 'prometheus-operator'"
      destination:
        ports: [8082]
  egress:
    - action: Allow # allowing application controller -> repo server to pull generated manifests
      protocol: TCP
      destination:
        selector: app.kubernetes.io/name == "argocd-repo-server"
        ports: [8081]
    - action: Allow # allowing application controller -> redis (HA Mode) for caching
      protocol: TCP
      destination:
        selector: app.kubernetes.io/name == "argocd-redis"
        ports: [6379]
