- name: Delete ArgoCD applications
  block:
  - name: Remove ArgoCD finalizer from kafka-operator Application
    ansible.builtin.shell: |
      kubectl patch application kafka-operator -n argocd -p '{"metadata":{"finalizers":null}}' --type=merge
    ignore_errors: true

  - name: Delete Kafka Operator Application
    kubernetes.core.k8s:
      api_version: argoproj.io/v1alpha1
      kind: Application
      name: kafka-operator
      namespace: argocd
      state: absent
      delete_options:
        propagationPolicy: Foreground

  - name: Remove ArgoCD finalizer from kafka-crds Application
    ansible.builtin.shell: |
      kubectl patch application kafka-crds -n argocd -p '{"metadata":{"finalizers":null}}' --type=merge
    ignore_errors: true

  - name: Delete Kafka CRDs Application
    kubernetes.core.k8s:
      api_version: argoproj.io/v1alpha1
      kind: Application
      name: kafka-crds
      namespace: argocd
      state: absent
      delete_options:
        propagationPolicy: Foreground
  
  - name: Delete KMinion Application
    kubernetes.core.k8s:
      api_version: argoproj.io/v1alpha1
      kind: Application
      name: kafka-metrics
      namespace: argocd
      state: absent
      delete_options:
        propagationPolicy: Foreground

- name: delete crds
  block:
    - name: Remove finalizers from KafkaTopics
      ansible.builtin.shell: |
        kubectl get kafkatopics -n kafka -l strimzi.io/cluster=cyphria-cluster -o name 2>/dev/null | \
        xargs -I {} kubectl patch {} -n kafka -p '{"metadata":{"finalizers":null}}' --type=merge 2>/dev/null || true
      ignore_errors: true

    - name: Delete KafkaTopics
      kubernetes.core.k8s:
        api_version: kafka.strimzi.io/v1beta2
        state: absent
        kind: KafkaTopic
        namespace: kafka
        label_selectors:
          - strimzi.io/cluster=cyphria-cluster

    - name: Remove finalizers from KafkaUsers
      ansible.builtin.shell: |
        kubectl get kafkausers -n kafka -l strimzi.io/cluster=cyphria-cluster -o name 2>/dev/null | \
        xargs -I {} kubectl patch {} -n kafka -p '{"metadata":{"finalizers":null}}' --type=merge 2>/dev/null || true
      ignore_errors: true

    - name: Delete KafkaUsers
      kubernetes.core.k8s:
        api_version: kafka.strimzi.io/v1beta2
        state: absent
        kind: KafkaUser
        namespace: kafka
        label_selectors:
          - strimzi.io/cluster=cyphria-cluster

    - name: Remove finalizers from KafkaNodePools
      ansible.builtin.shell: |
        kubectl get kafkanodepools -n kafka -l strimzi.io/cluster=cyphria-cluster -o name 2>/dev/null | \
        xargs -I {} kubectl patch {} -n kafka -p '{"metadata":{"finalizers":null}}' --type=merge 2>/dev/null || true
      ignore_errors: true

    - name: Delete KafkaNodePools
      kubernetes.core.k8s:
        api_version: kafka.strimzi.io/v1beta2
        state: absent
        kind: KafkaNodePool
        namespace: kafka
        label_selectors:
          - strimzi.io/cluster=cyphria-cluster

    - name: Remove finalizers from Kafka cluster
      ansible.builtin.shell: |
        kubectl patch kafka cyphria-cluster -n kafka -p '{"metadata":{"finalizers":null}}' --type=merge 2>/dev/null || true
      ignore_errors: true

    - name: Delete Kafka cluster
      kubernetes.core.k8s:
        api_version: kafka.strimzi.io/v1beta2
        state: absent
        kind: Kafka
        namespace: kafka
        name: cyphria-cluster

    - name: Delete Kafka persistent volumes
      kubernetes.core.k8s:
        state: absent
        kind: PersistentVolumeClaim
        namespace: kafka
        label_selectors:
          - strimzi.io/cluster=cyphria-cluster

- name: Force cleanup any remaining resources
  ansible.builtin.shell: |
    # Remove finalizers from all remaining resources in kafka namespace
    for resource in $(kubectl api-resources --verbs=list --namespaced -o name); do
      kubectl get "$resource" -n kafka -o name 2>/dev/null | \
      xargs -I {} kubectl patch {} -n kafka -p '{"metadata":{"finalizers":null}}' --type=merge 2>/dev/null || true
    done
  ignore_errors: true

- name: Delete Kafka namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: kafka
    state: absent

- name: Wait for Kafka namespace deletion
  ansible.builtin.shell: |
    timeout 120 bash -c 'while kubectl get namespace kafka 2>/dev/null; do sleep 2; done' || \
    kubectl get namespace kafka -o json | \
    jq '.spec.finalizers = []' | \
    kubectl replace --raw /api/v1/namespaces/kafka/finalize -f -
  ignore_errors: true