[project]
name = "Data_Process_Spark_Service"
version = "0.1.0"
description = "Python Code for Spark Structured Streaming"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.12.0",
    "pyspark>=4.0.1",
]
