apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.17.2

      helm: 
        valuesObject:
          prometheus:
            servicemonitor: 
              enabled: true
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          crds:
            enabled: true

    - repoURL: https://github.com/Vchen7629/Cyphria.git
      targetRevision: main
      path: kubernetes/cluster_roles/cert-manager/application

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
