apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls
  namespace: cert-manager
spec:
  secretName: cyphria-wildcard-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: cyphria.com
  dnsNames:
    - cyphria.com
    - '*.cyphria.com'
  duration: 2160h  # 90 days
  renewBefore: 360h # 15 days