---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: postgres
spec:
  selfSigned: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-ca
  namespace: postgres
  labels:
    cnpg.io/reload: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-ca
  namespace: postgres
spec:
  secretName: postgres-ca
  usages:
    - server auth
  dnsNames:
    - postgres-db-lb.internal.mydomain.net
    - postgres-db-rw
    - postgres-db-rw.default
    - postgres-db-rw.default.svc
    - postgres-db-r
    - postgres-db-r.default
    - postgres-db-r.default.svc
    - postgres-dbro
    - postgres-db-ro.default
    - postgres-db-ro.default.svc
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io