- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ item }}'
    tasks_from: facts
  loop:
    - k3s

- name: Role Reset
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Remove plugins
      kubernetes.core.helm_plugin:
        plugin_name: '{{ item.name }}'
        state: absent
      loop: '{{ helm_vars.plugins }}'
      when:
        - "'helm' in ansible_facts.packages"
        - "'python3-kubernetes' in ansible_facts.packages"
