- name: Role Facts
  ansible.builtin.import_tasks:
    file: facts.yaml
 
- name: Role Validation
  when: ('validation' in ansible_run_tags)
  run_once: true
  block:
     - name: validate inventory
       ansible.builtin.assert:
         that: k3s_map.server.ha is truthy or k3s_map.server.non_ha is truthy
         fail_msg: |-
           ERROR: Invalid number of 'server' type nodes.
             - Defined nodes: {{ k3s_map.server.hosts | length }} ({{ k3s_map.server.hosts | join(', ') }})
             - valid values: 1 or higher than 2
           Fixes:
             - update the number of 'server' type nodes, into inventory file.
         quiet: true
     