- name: Post Install configuration
  run_once: true
  block:
    - name: Restart Pods for tls certs to take effect
      ansible.builtin.command:
        cmd: kubectl -n argocd rollout restart deployment {{ deployment }}
      loop:
        - argo-cd-argocd-repo-server
        - argo-cd-argocd-dex-server
      loop_control:
        loop_var: deployment

    - name: Add User Account
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        definition: "{{ lookup('ansible.builtin.template', 'credentials.j2') | from_yaml }}"
        wait: true