- name: Role Reset
  block:
    - name: Remove Repo
      kubernetes.core.helm_repository:
        name: '{{ argocd_vars.kubernetes.helm.repository.org }}'
        repo_state: absent
  
    - name: remove binary
      ansible.builtin.file: 
        path: /usr/local/bin/argocd
        state: absent
    
    - name: Delete argocd StatefulSet
      kubernetes.core.k8s:
        state: absent
        api_version: apps/v1
        kind: StatefulSet
        name: argo-cd-argocd-application-controller
        namespace: argocd # adjust namespace if needed

    - name: Delete Prometheus Operator Deployment
      kubernetes.core.k8s:
        state: absent
        api_version: apps/v1
        kind: Deployment
        name: "{{ item }}"
        namespace: argocd
      loop:
        - argo-cd-argocd-applicationset-controller
        - argo-cd-argocd-dex-server
        - argo-cd-argocd-redis
        - argo-cd-argocd-notifications-controller
        - argo-cd-argocd-repo-server
        - argo-cd-argocd-server

    - name: Delete Pod Services
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Service
        name: "{{ item }}"
        namespace: argocd # adjust namespace if needed
      loop:
        - argo-cd-argocd-application-controller-metrics
        - argo-cd-argocd-applicationset-controller
        - argo-cd-argocd-dex-server
        - argo-cd-argocd-redis
        - argo-cd-argocd-redis-metrics
        - argo-cd-argocd-repo-server
        - argo-cd-argocd-repo-server-metrics
        - argo-cd-argocd-server
        - argo-cd-argocd-server-metrics

    - name: Delete ArgoCD Certificate resources
      ansible.builtin.command:
        cmd: "{{ certificate_resource }}"
      loop:
        - kubectl delete certificate argocd-repo-tls -n argocd
        - kubectl delete certificate argocd-dex-tls -n argocd
        - kubectl delete certificate argocd-server-tls -n argocd
      loop_control:
        loop_var: certificate_resource
      ignore_errors: true
    
    - name: Delete ArgoCD Secrets resources
      ansible.builtin.command:
        cmd: "{{ secret_resource }}"
      loop:
        - kubectl delete secrets argocd-repo-server-tls -n argocd
        - kubectl delete secrets argocd-dex-server-tls -n argocd
        - kubectl delete secrets argocd-server-tls -n argocd
      loop_control:
        loop_var: secret_resource
      ignore_errors: true