- name: Configure namespaces
  ansible.builtin.import_tasks:
    file: namespaces.yaml
  any_errors_fatal: true


- name: Configure Network Policies
  block:    
    - name: Apply ArgoCD Server Network Policy
      ansible.builtin.shell:
        cmd: "calicoctl apply -f -"
        stdin: "{{ lookup('file', item) }}"
      with_items:
        - "{{ role_path }}/templates/server.yaml" 
        - "{{ role_path }}/templates/repo-server.yaml"
        - "{{ role_path }}/templates/redis.yaml"
        - "{{ role_path }}/templates/dex-server.yaml"
        - "{{ role_path }}/templates/applicationset-controller.yaml"
        - "{{ role_path }}/templates/application-controller.yaml"
      register: result
      retries: 3
      delay: 1
      until: result is not failed
  
    - name: Apply Applications network Policy
      ansible.builtin.shell:
        cmd: "calicoctl apply -f -"
        stdin: "{{ lookup('file', item) }}"
      with_items:
        - "{{ role_path }}/templates/nginx.yaml"
        - "{{ role_path }}/templates/prometheus-operator.yaml"
        - "{{ role_path }}/templates/frontend.yaml" 
        - "{{ role_path }}/templates/cloudflare-tunnel.yaml"
        - "{{ role_path }}/templates/external-dns.yaml"
        - "{{ role_path }}/templates/cert-manager.yaml"
        - "{{ role_path }}/templates/postgres.yaml"
      register: result
      retries: 3
      delay: 1
      until: result is not failed    
    
    - name: Apply default deny all Policy
      ansible.builtin.shell: 
        cmd: "calicoctl create -f -"
        stdin: "{{ lookup('file', role_path + '/templates/deny-all.yaml') }}"
    
    
          

        