
- name: Role Provisioning
  when: inventory_hostname in k3s_map.server.hosts
  block:
  - name: Ensure curl is installed for Helm script
    ansible.builtin.apt:
      name: curl
      state: present
      update_cache: yes
    become: true
  
  - name: Install packages
    ansible.builtin.apt:
      name: '{{ item }}'
      autoremove: true
      update_cache: true
    loop:
      - apt-transport-https
      - python3-kubernetes

  - name: install k3s binary
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      dest: /tmp/helm-installer.sh
      owner: root
      group: root
      mode: '755'
    register: result
    delay: 1
    retries: 3
    until: result is not failed
  
  - name: execute binary
    ansible.builtin.command: /tmp/helm-installer.sh
    become: true

  - name: Remove Helm installer script
    ansible.builtin.file:
      path: /tmp/helm-installer.sh
      state: absent