---
kafka_vars:
  kubernetes:
    helm_operator:
      chart:
        name: strimzi-kafka-operator
        version: "0.48.0"
      repository:
        name: strimzi-kafka-operator
        url: oci://quay.io/strimzi-helm
    helm_metrics:
      chart:
        name: kminion
        version: "0.14.2"
      repository:
        url: https://charts.redpanda.com
    namespace: kafka
    replicas: 1
    node: tachyon-optiplex-3050
    operator_resources:
      limits:
        cpu: null
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 512Mi
    metrics:
      limits:
        cpu: 100m
        memory: 128mi
      requests:
        cpu: 100m
        memory: 128mi