apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/deployment.yaml
  - base/service.yaml
  - base/autoscaler.yaml

images:
  - name: ghcr.io/vchen7629/cyphria-frontend
    newTag: latest