# To enable HA just add in more than one host in the server.hosts #
server: # 
  hosts:
    tiamat:
      ansible_host: 10.0.0.167
      ansible_user: root
      ansible_password: 5526
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_become_password: 5526
    #ryujin:

    #tachyon:

agent:
  tempest:
  fafnir:
  glaurung:
  bahumat:
  nidhog:

cluster:
  children:
    server:
    agent:
