apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: argocd-application-controller-network-policy
  namespace: argocd
spec:
  order: 80
  selector: "app.kubernetes.io/name == 'argocd-application-controller' ||
             app.kubernetes.io/name == 'argocd-metrics'"
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow # exposing ArgoCD application controller metrics endpoint
      protocol: TCP
      source:
        namespaceSelector: projectcalico.org/name == "prometheus"
        selector: all() # fix later, find out what labels exactly
      destination:
        ports: [8082]
  egress:
    - action: Allow # DNS lookups
      protocol: UDP
      destination:
        selector: k8s-app == "kube-dns"
        namespaceSelector: projectcalico.org/name == "kube-system"
        ports: [53]
    - action: Allow # DNS lookups (TCP)
      protocol: TCP
      destination:
        selector: k8s-app == "kube-dns"
        namespaceSelector: projectcalico.org/name == "kube-system"
        ports: [53]
    - action: Allow # Kubernetes API access
      protocol: TCP
      destination:
        services:
          namespace: default
          name: kubernetes
    - action: Allow # allowing application controller -> repo server to pull generated manifests
      protocol: TCP
      destination:
        selector: app.kubernetes.io/name == "argocd-repo-server"
        ports: [8081]
    - action: Allow # allowing application controller -> redis (HA Mode) for caching
      protocol: TCP
      destination:
        selector: app.kubernetes.io/name == "argocd-redis"
        ports: [6379]
