apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: argocd-applicationset-controller-network-policy
  namespace: argocd
spec:
  order: 80
  selector: app.kubernetes.io/name == "argocd-applicationset-controller"
  types:
    - Egress
  egress:
    - action: Allow # DNS lookups
      protocol: UDP
      destination:
        selector: k8s-app == "kube-dns"
        namespaceSelector: projectcalico.org/name == "kube-system"
        ports: [53]
    - action: Allow # DNS lookups (TCP)
      protocol: TCP
      destination:
        selector: k8s-app == "kube-dns"
        namespaceSelector: projectcalico.org/name == "kube-system"
        ports: [53]
    - action: Allow # Kubernetes API access
      protocol: TCP
      destination:
        services:
          namespace: default
          name: kubernetes
    - action: Allow # Allowing ArgoCD applicationset -> ArgoCD repo server for template processing
      protocol: TCP
      destination:
        selector: app.kubernetes.io/name == "argocd-repo-server"
        ports: [8081]