- name: Deploy Cloudnative Postgres Opeator Helm Chart
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'argo-cd-deployment.yaml') | from_yaml }}"
    kubeconfig: /etc/rancher/k3s/k3s.yaml