- name: Uninstall Cert manager in argocd
  kubernetes.core.k8s:
    api_version: argoproj.io/v1alpha1
    state: absent
    kind: Application
    name: cert-manager
    namespace: argocd

- name: Delete ArgoCD Secrets resourcs
  ansible.builtin.command:
    cmd: "{{ certificate_resource }}"
  loop:
    - kubectl -n cert-manager delete certificaterequests -l cert-manager.io/certificate-name=argocd-repo-tls
    - kubectl -n cert-manager delete certificaterequests -l cert-manager.io/certificate-name=argocd-dex-tls
    - kubectl -n cert-manager delete certificaterequests -l cert-manager.io/certificate-name=argocd-server-tls
    - kubectl -n cert-manager delete certificaterequests -l cert-manager.io/certificate-name=postgres-db-tls
    - kubectl -n cert-manager delete certificaterequests -l cert-manager.io/certificate-name=postgres-ca
    - kubectl -n cert-manager delete orders -l cert-manager.io/certificate-name=argocd-repo-tls
    - kubectl -n cert-manager delete orders -l cert-manager.io/certificate-name=argocd-dex-tls
    - kubectl -n cert-manager delete orders -l cert-manager.io/certificate-name=argocd-server-tls
    - kubectl -n cert-manager delete orders -l cert-manager.io/certificate-name=postgres-tls
  loop_control:
    loop_var: certificate_resource
  ignore_errors: true
