name: Create GHCR container

on: 
    schedule: 
        - cron: '59 11 * * *'
    push:
        branches:
            - main
    
permissions:
    packages: write

jobs:
    build-and-push-frontend-image:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3 # v3.0.0

            - name: Log into registry $https://ghcr.io
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v3 # v3.0.0
              with:
                registry: https://ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Build and push Docker image
              id: build-and-push
              uses: docker/build-push-action@v5
              with:
                context: ./frontend
                file: ./frontend/Dockerfile
                push: true
                tags: ghcr.io/vchen7629/atlaxiom-frontend:prod
                cache-from: type=registry,ref=ghcr.io/vchen7629/frontend-npm-cache:latest
