name: Create Login Api GHCR container

on:
  push:
    branches:
      - main
    paths:
      - 'loginapi/**'
  
permissions:
  packages: write

jobs:
  create-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # v3.0.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3 # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Env file
        uses: SpicyPizza/create-envfile@v2.0
        with: 
          envKey_DATABASEURI: ${{ secrets.Postgres_DB_URI }}
          envKey_Redis_DB: ${{ secrets.Redis_DB }}
          envKey_Redis_Addr: ${{ secrets.Redis_Addr }}
          envKey_Redis_Password: ${{ secrets.Redis_Password }}
          directory: .
          file_name: .env
          fail_on_empty: true
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./loginapi
          file: ./loginapi/dockerfile
          push: true
          tags: ghcr.io/vchen7629/loginapi:latest