name: Create Reddit Data Ingestion Service GHCR container

on: 
  push:
    branches:
      - main
    paths:
      - 'data-processing-pipeline/reddit-api-data-ingestion/**'

permissions:
  packages: write

jobs:
  create-container:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
            
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3 # v3.0.0

        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v3 # v3.0.0
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: ./data-processing-pipeline/reddit-api-data-ingestion
            file: ./reddit-api-data-ingestion/dockerfile
            push: true
            tags: ghcr.io/vchen7629/reddit-api-data-ingestion-service:latest