apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-operator
  namespace: kafka
spec:
  project: default
  sources:
    - chart: '{{ kafka_vars.kubernetes.helm.chart.name }}'
      repoURL: '{{ kafka_map.helm.repository.url }}'
      targetRevision: '{{ kafka_vars.kubernetes.helm.chart.version }}'

      helm:
        valuesObject:
          replicas: '{{ kafka_vars.kubernetes.replicas }}'
          dashboards:
            enabled: true
            namespace: kafka
            label: kafka_grafana_dashboard 
            labelValue: "1"
            annotations: {}
            extraLabels: {}
          resources:
              limits:
                  cpu: '{{ kafka_vars.kubernetes.operator_resources.limits.cpu }}'
                  memory: '{{ kafka_vars.kubernetes.operator_resources.limits.memory }}'
              requests:
                  cpu: '{{ kafka_vars.kubernetes.operator_resources.requests.cpu }}'
                  memory: '{{ kafka_vars.kubernetes.operator_resources.limits.memory }}'

  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true