apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: '{{ kafka_map.helm_operator.repository.url }}'
    targetRevision: '{{ kafka_vars.kubernetes.helm_operator.chart.version }}'
    chart: '{{ kafka_vars.kubernetes.helm_operator.chart.name }}'

    helm:
      valuesObject:
        replicas: '{{ kafka_vars.kubernetes.replicas }}'

        resources:
          limits:
              memory: '{{ kafka_vars.kubernetes.operator_resources.limits.memory }}'
          requests:
              cpu: '{{ kafka_vars.kubernetes.operator_resources.requests.cpu }}'
              memory: '{{ kafka_vars.kubernetes.operator_resources.requests.memory }}'

  destination:
    server: https://kubernetes.default.svc
    namespace: kafka

  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true